### ISSUE TITLE
Error after update 4.0.6 to 4.0.9

### ISSUE THREAD

**Issue by usebaz** [TryGhost/node-sqlite3#1185]
After update `sqlite3` from `4.0.6` to `4.0.9`, application crash with error:
```
TypeError: Cannot read property 'prototype' of undefined
    at inherits (/app-test/node_modules/sqlite3/lib/sqlite3.js:27:16)
    at Object.<anonymous> (/app-test/node_modules/sqlite3/lib/sqlite3.js:66:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at ConnectionManager._loadDialectModule (/app-test/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:74:14)
    at new ConnectionManager (/app-test/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/app-test/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/app-test/node_modules/sequelize/lib/sequelize.js:320:20)
    at MySQLInitializer.initialize (/app-test/initializers/mysql.js:24:25)
    at Utils.initializeFunction (/app-test/node_modules/actionhero/classes/process.js:138:31)
    at Object.api.utils.asyncWaterfall (/app-test/node_modules/actionhero/initializers/utils.js:77:31)
```
Node: `10.15.1`
npm: `6.7.0`
OS: `SunOS Solaris 11.4.5.3.0`

**Comment by kewde** [comment]
Need a simple code example for the failure, thanks.

**Comment by usebaz** [comment]
@kewde It fail on initializing:
```
api.config.mysql = {
  user: 'some_user',
  password: 'some_pass',
  database: 'some_db',
  host: 'some_host',
  port: 3306,
  pool: {
      maxConnections: 20,
      maxIdleTime: 30000,
  },
  charset: 'utf8mb4',
  timezone: '+00:00',

  dialectOptions: { decimalNumbers: true },
  dialect: 'sqlite',
  storage: ':memory:',
  omitNull: true,
  logging: false,
};

const { database, user, password } = api.config.mysql;
api.config.mysql.logging = (text, params) => {
    api.logger.info(`${text}. Bind: [${params.bind || []}]`);
};

const sequelize = new Sequelize(database, user, password, api.config.mysql); // FAIL HERE
```

**Comment by kewde** [comment]
This is an SQLite library, I don't understand what all this MySQL related configuration code is doing in there?

**Comment by usebaz** [comment]
https://www.npmjs.com/package/sequelize use SQLite  as dialect. If I update only sqlite from 4.0.6 to 4.0.9 it cause fail on Solaris

**Comment by ggravarr** [comment]
I have this same issue using this module as a test mock for native sqlite in a react native project. If I comment out `inherits(Backup, EventEmitter);` on line 62 in `lib/sqlite3.js` it doesn't throw with `Cannot read property 'prototype' of undefined` and what functionality I use for my test mocks completes without issue. my binding is `node-v64-darwin-x64`. I'm just sticking with `4.0.6` for now.

**Comment by ggravarr** [comment]
nevermind, running node-pre-gyp reinstall in the sqlite3 node_module folder fixes this for me. I'm guessing I was hitting an old local cache.
