### ISSUE TITLE
npm/rethinkdb/node.js crashing after reboot

### ISSUE THREAD

**Issue by itsmeMettyu** [TryGhost/node-sqlite3#1204]
I am a little bit newbie in these things. I do some web coding at school only. I found a contest a few days ago. I setuped the backend, I just need to make the frontend. I have a digital ocean droplet and after a reboot I got an npm error when I want to run the `npm with npm run start-production` The git is here:

`https://github.com/BobTheShoplifter/lootvgo-opensource/blob/master/auto-instructions.md
`
And here is the error log:

```
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start-production' ]
> 2 info using npm@6.9.0
> 3 info using node@v10.16.0
> 4 verbose run-script [ 'prestart-production',
> 4 verbose run-script   'start-production',
> 4 verbose run-script   'poststart-production' ]
> 5 info lifecycle lootvgo-backend@1.0.1~prestart-production: lootvgo-backend@1.0.1
> 6 info lifecycle lootvgo-backend@1.0.1~start-production: lootvgo-backend@1.0.1
> 7 verbose lifecycle lootvgo-backend@1.0.1~start-production: unsafe-perm in lifecycle true
> 8 verbose lifecycle lootvgo-backend@1.0.1~start-production: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/lootvgo-opensource/backend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 9 verbose lifecycle lootvgo-backend@1.0.1~start-production: CWD: /root/lootvgo-opensource/backend
> 10 silly lifecycle lootvgo-backend@1.0.1~start-production: Args: [ '-c',
> 10 silly lifecycle   'NODE_ENV=production npm run db-setup && pm2 startOrRestart ecosystem.json --max-memory-restart 8G && pm2 save' ]
> 11 silly lifecycle lootvgo-backend@1.0.1~start-production: Returned: code: 1  signal: null
> 12 info lifecycle lootvgo-backend@1.0.1~start-production: Failed to exec start-production script
> 13 verbose stack Error: lootvgo-backend@1.0.1 start-production: `NODE_ENV=production npm run db-setup && pm2 startOrRestart ecosystem.json --max-memory-restart 8G && pm2 save`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
> 13 verbose stack     at EventEmitter.emit (events.js:198:13)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:198:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 14 verbose pkgid lootvgo-backend@1.0.1
> 15 verbose cwd /root/lootvgo-opensource/backend
> 16 verbose Linux 4.4.0-157-generic
> 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start-production"
> 18 verbose node v10.16.0
> 19 verbose npm  v6.9.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error lootvgo-backend@1.0.1 start-production: `NODE_ENV=production npm run db-setup && pm2 startOrRestart ecosystem.json --max-memory-restart 8G && pm2 save`
> 22 error Exit status 1
> 23 error Failed at the lootvgo-backend@1.0.1 start-production script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
```

**Comment by daniellockyer** [comment]
Please try with v5.0.3 🙂
