### ISSUE TITLE
Electron v8.3.3 build from source failed

### ISSUE THREAD

**Issue by mia1024** [TryGhost/node-sqlite3#1349]
I tried to build from the source for electron v8.3.3 but failed with the following error, similar to #612. I also tried `electron-rebuild` and `electron-builder install-app-deps`, both of which gave the same errors. 

```sh
# npm rebuild sqlite3 --target=8.3.3 --runtime=electron --dist-url=https://atom.io/download/electron --update-binary --abi=76 --unsafe-perm

> sqlite3@4.2.0 install /root/restructured-notes/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/electron-v8.3-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and electron@8.3.3 (electron-v8.3 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/root/restructured-notes/node_modules/sqlite3/build'
make: *** No rule to make target '../deps/sqlite-autoconf-3310100.tar.gz', needed by 'Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c'.  Stop.
make: Leaving directory '/root/restructured-notes/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-88-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/restructured-notes/node_modules/sqlite3/lib/binding/electron-v8.3-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/root/restructured-notes/node_modules/sqlite3/lib/binding/electron-v8.3-linux-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v8.3"
gyp ERR! cwd /root/restructured-notes/node_modules/sqlite3
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/restructured-notes/node_modules/sqlite3/lib/binding/electron-v8.3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/restructured-notes/node_modules/sqlite3/lib/binding/electron-v8.3-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v8.3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/restructured-notes/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.15.0-88-generic
node-pre-gyp ERR! command "/usr/bin/node" "/root/restructured-notes/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/restructured-notes/node_modules/sqlite3
node-pre-gyp ERR! node -v v12.18.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/restructured-notes/node_modules/sqlite3/lib/binding/electron-v8.3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/restructured-notes/node_modules/sqlite3/lib/binding/electron-v8.3-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v8.3' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I have tried to upgrade to the latest version via `npm install --global npm@latest` but it didn't work. Tried on both Ubuntu 18.04 with gcc v7.5.0 and macOS 10.14.6 with clang 11.0.0. I'm using sqlite3 4.2.0.

**Comment by pkqxdd** [comment]
A temporary solution I found was setting the target to be 8.2.0, since there was a pre-built binary and that, according to [node abi registry](https://github.com/nodejs/node/blob/c8df5cf74a2b495ccbc8b25a29c1692391c505f3/doc/abi_version_registry.json#L6), the entire electron v8 shares the same API. Then I copied `node_modules/sqlite3/lib/binding/electron-v8.2-darwin-x64/node_sqlite3.node` into `node_modules/sqlite3/lib/binding/electron-v8.3-darwin-x64/node_sqlite3.node`, which made it work on my computer...for now. I think a better solution would be, if we can't compile it, at least have some pre-built binaries for electron v8.3. In theory it should be the same as the ones for 8.2.x, but I don't really know how to work with `node-pre-gyp` to submit it.

**Comment by kewde** [comment]
Try v5.0.0

**Comment by pkqxdd** [comment]
> Try v5.0.0

Same error.

**Comment by pkqxdd** [comment]
So far I have been using this shell script to install sqlite3 for my project
```sh
rebuild_sqlite3() {
  npm rebuild sqlite3 --target=8.2.3 --runtime=electron --dist-url='https://atom.io/download/electron' --update-binary
  if [ $? -ne 0 ]; then
    errorMessage 'cannot rebuild sqlite3'
    exit 1
  fi
  platform=$(uname)
  oldPath="node_modules/sqlite3/lib/binding/electron-v8.2-$(echo $platform | awk '{print tolower($0)}')-x64/node_sqlite3.node"
  newPath="node_modules/sqlite3/lib/binding/electron-v8.3-$(echo $platform | awk '{print tolower($0)}')-x64/node_sqlite3.node"
  mkdir -p "node_modules/sqlite3/lib/binding/electron-v8.3-$(echo $platform | awk '{print tolower($0)}')-x64/"
  cp "$oldPath" "$newPath"
}
```
It's a bit hackish but at least it works.

**Comment by TylerJNewman** [comment]
upgrading to sqlite3 v5.0.0 worked for me... thanks
https://stackoverflow.com/a/50112270/4722811

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
