### ISSUE TITLE
Error compiling for electron 8.4.0

### ISSUE THREAD

**Issue by ajmasia** [TryGhost/node-sqlite3#1356]
I'm tryin to compile to use sqlcipher with electron 8.4.0 with node 10.19.0 using this command:

`npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=brew --prefix --runtime=electron --target=8.4.0 --dist-url=https://electronjs.org/headers`

Previosuly I've installed sqlcipher with brew and config:

```bash
export LDFLAGS="-L`brew --prefix`/opt/sqlcipher/lib"
export CPPFLAGS="-I`brew --prefix`/opt/sqlcipher/include"
```

An i get this error:

```bash
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> sqlite3@5.0.0 install /Users/.../--runtime=electron/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
action_after_build.target.mk:8: *** commands commence before first target.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/.../.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/.../.nvm/versions/node/v10.19.0/bin/node" "/Users/.../.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/.../--runtime=electron/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/.../--runtime=electron/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /Users/.../--runtime=electron/node_modules/sqlite3
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/.../.nvm/versions/node/v10.19.0/bin/node /Users/.../.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/.../--runtime=electron/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/.../--runtime=electron/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/.../--runtime=electron/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.5.0
node-pre-gyp ERR! command "/Users/.../.nvm/versions/node/v10.19.0/bin/node" "/Users/.../--runtime=electron/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/.../--runtime=electron/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/.../.nvm/versions/node/v10.19.0/bin/node /Users/.../.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/.../--runtime=electron/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/.../--runtime=electron/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN enoent ENOENT: no such file or directory, open '/Users/.../--runtime=electron/package.json'
npm WARN --runtime=electron No description
npm WARN --runtime=electron No repository field.
npm WARN --runtime=electron No README data
npm WARN --runtime=electron No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/../.npm/_logs/2020-07-14T14_58_10_018Z-debug.log
```

Any idea? 
Thanks!

**Comment by mtgto** [comment]
```
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=brew --prefix --runtime=electron --target=8.4.0 --dist-url=https://electronjs.org/headers
```

Try

```
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=`brew --prefix` --runtime=electron --target=8.4.0 --dist-url=https://electronjs.org/headers
```

https://github.com/mapbox/node-sqlite3#on-os-x-with-homebrew

**Comment by i-chaochen** [comment]
> ```
> npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=brew --prefix --runtime=electron --target=8.4.0 --dist-url=https://electronjs.org/headers
> ```
> 
> Try
> 
> ```
> npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=`brew --prefix` --runtime=electron --target=8.4.0 --dist-url=https://electronjs.org/headers
> ```
> 
> https://github.com/mapbox/node-sqlite3#on-os-x-with-homebrew

None of the two work.

I tried the solution from https://github.com/mapbox/node-sqlite3#on-os-x-with-homebrew
```
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=`brew --prefix` --runtime=electron --target=1.7.6 --dist-url=https://electronjs.org/headers
```

Still the same problem cannot find the module.

```
Uncaught Error: Cannot find module '../node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node'
```

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
