### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mauricedoepke** [TryGhost/node-sqlite3#1360]
Seems like there are problems with spaces in file path.

```
An unhandled error has occurred inside Forge:
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.1 | win32 | x64
gyp info find Python using Python version 3.8.4 found at "C:\Program Files\Python38\python.exe"
gyp info find VS using VS2019 (16.5.30011.22) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python38\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Maurice Döpke\\.electron-gyp\\8.2.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Maurice Döpke\\.electron-gyp\\8.2.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Maurice Döpke\\\\.electron-gyp\\\\8.2.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\sqlite3\build\Release\\nothing.lib
  unpack_sqlite_dep
  'C:\Program' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=8.2.2" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\sqlite3\\lib\\binding\\napi-v{napi_build_version}-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v5.0.0/{toolset}/" "--package_name=napi-v{napi_build_version}-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\sqlite3
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.1 | win32 | x64
gyp info find Python using Python version 3.8.4 found at "C:\Program Files\Python38\python.exe"
gyp info find VS using VS2019 (16.5.30011.22) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python38\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Maurice Döpke\\.electron-gyp\\8.2.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Maurice Döpke\\.electron-gyp\\8.2.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Maurice Döpke\\\\.electron-gyp\\\\8.2.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\sqlite3\build\Release\\nothing.lib
  unpack_sqlite_dep
  'C:\Program' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=8.2.2" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Public\\projects\\michael-hawthorne-image-db-tool\\application\\node_modules\\sqlite3\\lib\\binding\\napi-v{napi_build_version}-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v5.0.0/{toolset}/" "--package_name=napi-v{napi_build_version}-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\sqlite3
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\spawn-rx\src\index.ts:296:18)
    at SafeSubscriber.__tryOrUnsub (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:265:10)
    at SafeSubscriber.error (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:220:16)
    at Subscriber._error (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:143:22)
    at Subscriber.error (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:113:12)
    at MapSubscriber.Subscriber._error (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:143:22)
    at MapSubscriber.Subscriber.error (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:113:12)
    at SafeSubscriber._next (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\spawn-rx\src\index.ts:265:42)
    at SafeSubscriber.__tryOrUnsub (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:265:10)
    at SafeSubscriber.next (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:207:14)
    at Subscriber._next (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:139:22)
    at Subscriber.next (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at DefaultIfEmptySubscriber._next (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\operators\defaultIfEmpty.ts:75:22)
    at DefaultIfEmptySubscriber.Subscriber.next (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at TakeLastSubscriber._complete (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\operators\takeLast.ts:108:21)
    at TakeLastSubscriber.Subscriber.complete (C:\Users\Public\projects\michael-hawthorne-image-db-tool\application\node_modules\rxjs\src\internal\Subscriber.ts:126:12)
error Command failed with exit code 1.
```

**Comment by yildiraykoyuncu** [comment]
I am receiving a similar error of   'c:\Program' is not recognized as an internal or external command,
  operable program or batch file' .

Any solutions for that?

```Specify configs in the ini-formatted file:
PS C:\Users\k\Desktop\yk\HYF\restful-chinook> npm install

> sqlite3@4.2.0 install C:\Users\k\Desktop\yk\HYF\restful-chinook\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.1.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  'c:\Program' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\k\Desktop\yk\HYF\restful-chinook\node_m
odules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\k\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\k\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\k\\Desktop\\yk\\HYF\\restful-chinook\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\k\\Desktop\\yk\\HYF\\restful-chinook\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd C:\Users\k\Desktop\yk\HYF\restful-chinook\node_modules\sqlite3
gyp ERR! node -v v14.1.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\k\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\k\Desktop\yk\HYF\restful-chinook\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\k\Desktop\yk\HYF\restful-chinook\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\k\Desktop\yk\HYF\restful-chinook\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\k\\Desktop\\yk\\HYF\\restful-chinook\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\k\Desktop\yk\HYF\restful-chinook\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\k\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\k\Desktop\yk\HYF\restful-chinook\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\k\Desktop\yk\HYF\restful-chinook\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN refactored-dynamic-example@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\k\AppData\Roaming\npm-cache\_logs\2020-11-21T14_23_44_617Z-debug.log
PS C:\Users\k\Desktop\yk\HYF\restful-chinook>```

**Comment by w4ngzhen** [comment]
In fact, I've reinstalled my VS and Node programs, installing them in a path that doesn't contain Spaces. Then the problem was solved. I think when Node-gyp calls MSBuild, after getting the path, it's called directly from the command line.

**Comment by ItsIgnacioPortal** [comment]
This shouldn't be an issue in the first place. The default installation path for Visual Studio is under Program Files, and moving Visual Studio is not a small task at all.

**Comment by ItsIgnacioPortal** [comment]
This particular issue completely breaks Ghost on Windows. The last version that I've known to work is Ghost v4.41.3

**Comment by ItsIgnacioPortal** [comment]
Alright, so with this little go program that I named `Program.go`, I was able to obtain the parameters of whathever tried to incorrectly run something from Program Files:

```go
package main

import "os"
import "fmt"
import "strings"

func main() {
	filename := "C:\\Users\\Sherman\\Desktop\\access-log.txt"
	myFlags := os.Args[1:]
	fmt.Println(myFlags)

	myFlagsString := strings.Join(myFlags, " ")

	f, err := os.OpenFile(filename, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0644)
	if err != nil {
		panic(err)
	}

	defer f.Close()

	if _, err = f.WriteString(myFlagsString + "\r\n"); err != nil {
		panic(err)
	}
}
```

I compiled the program, and moved it to "C:\Program.exe". After running `npm install @vscode/sqlite3 --save`, these were the contents of `C:\\Users\\Sherman\\Desktop\\access-log.txt`:

```
Files\Python37\python.exe ../../deps/extract.py ../../deps/sqlite-autoconf-3360000.tar.gz C:\Users\Sherman\node_modules\@vscode\sqlite3\build\Release\obj/global_intermediate
```

So, something wanted to run:
`C:\Program Files\Python37\python.exe ../../deps/extract.py ../../deps/sqlite-autoconf-3360000.tar.gz C:\Users\Sherman\node_modules\@vscode\sqlite3\build\Release\obj/global_intermediate`

but because the path to `python.exe` wasn't quoted, it actually ran:
`C:\Program.exe Files\Python37\python.exe ../../deps/extract.py ../../deps/sqlite-autoconf-3360000.tar.gz C:\Users\Sherman\node_modules\@vscode\sqlite3\build\Release\obj/global_intermediate`

I hope this can help the devs ( @daniellockyer ) solve this 😁

**Comment by daniellockyer** [comment]
Hey @ItsIgnacioPortal 🙂 This should be resolved with https://github.com/TryGhost/node-sqlite3/commit/8db96d42be7f7aba506d04018cf6cbdc1bfa3373, which switches away from using Python found via `node-gyp`.

I'm also one of the developers of Ghost and we were forced to switch to `@vscode/sqlite3` because this repo was becoming unmaintained. Once it's fixed up and a new version is released, we should be able to switch back - therefore fixing the issue for yourself 🙂
