### ISSUE TITLE
is it expected behavior fo native-module to have arbitrary read-only properties in strict-mode?

### ISSUE THREAD

**Issue by kaizhu256** [TryGhost/node-sqlite3#1372]
the native module `node_sqlite3.node` behaves differently in sloppy/strict mode.  i can't directly modify Database and Statement methods in strict-mode.

the below shell-script throws an error when i try to override Statement methods with additional tracing in strict-mode.

```bash
#!/bin/sh
# sqlite3_test.sh

# download sqlite3-native-module
node -e '
let file;
file = "napi-v3-" + process.platform + "-" + process.arch;
console.error(
    "sqlite3 - fetching "
    + "https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/"
    + file + ".tar.gz"
);
require("child_process").spawnSync((
    "curl -A \"chrome\" -Lf "
    + "https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/"
    + file + ".tar.gz "
    + "| tar -O -xz " + file + "/node_sqlite3.node "
    + "> .node_sqlite3-v5.0.0-" + file + ".node"
), {
    encoding: "utf8",
    shell: true,
    stdio: [
        "ignore", 1, 2
    ]
});
'


# sloppy-mode - add trace-debug to sqlite3-native-module
node -e '
let sqlite3 = require(
    "./.node_sqlite3-v5.0.0-" + "napi-v3-"
    + process.platform + "-" + process.arch + ".node"
);
let old = sqlite3.Statement.prototype.run;
sqlite3.Statement.prototype.run = function (...argList) {
    console.error(new Error().stack);
    return old.apply(this, argList);
};
'


# strict-mode - add trace-debug to sqlite3-native-module
node -e '
"use strict";
let sqlite3 = require(
    "./.node_sqlite3-v5.0.0-" + "napi-v3-"
    + process.platform + "-" + process.arch + ".node"
);
let old = sqlite3.Statement.prototype.run;
sqlite3.Statement.prototype.run = function (...argList) {
    console.error(new Error().stack);
    return old.apply(this, argList);
};
'
# output:
# TypeError: Cannot assign to read only property 'run' of object '#<Statement>'
#     at [eval]:8:33
# ?[90m    at Script.runInThisContext (vm.js:120:18)?[39m
# ?[90m    at Object.runInThisContext (vm.js:309:38)?[39m
#     at Object.<anonymous> ([eval]-wrapper:10:26)
# ?[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)?[39m
# ?[90m    at evalScript (internal/process/execution.js:94:25)?[39m
# ?[90m    at internal/main/eval_string.js:23:3?[39m

```

**Comment by daniellockyer** [comment]
I believe this should be fixed with https://github.com/TryGhost/node-sqlite3/commit/c366ef9fdca05bc6ea899207da6e62a146f8012d
