### ISSUE TITLE
debug log - what's it for?

### ISSUE THREAD

**Issue by working-name** [TryGhost/node-sqlite3#1377]
Trying to install this in debian 10 running in WSL2. 

To a regular joe shmoe like me this says absolutely nothing. No idea what to try, no idea why it failed. It's rather... cryptic. How do you use the debug log?

```
13450 verbose stack Error: sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
13450 verbose stack Exit status 1
13450 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13450 verbose stack     at EventEmitter.emit (events.js:193:13)
13450 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13450 verbose stack     at ChildProcess.emit (events.js:193:13)
13450 verbose stack     at maybeClose (internal/child_process.js:999:16)
13450 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
13451 verbose pkgid sqlite3@3.1.13
13452 verbose cwd /mnt/c/Users/owner/Documents/Projects/goodboy
13453 verbose Linux 4.19.104-microsoft-standard
13454 verbose argv "/root/.nvm/versions/node/v11.15.0/bin/node" "/root/.nvm/versions/node/v11.15.0/bin/npm" "i" "sqlite3"
13455 verbose node v11.15.0
13456 verbose npm  v6.7.0
13457 error code ELIFECYCLE
13458 error errno 1
13459 error sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
13459 error Exit status 1
13460 error Failed at the sqlite3@3.1.13 install script.
13460 error This is probably not a problem with npm. There is likely additional logging output above.
13461 verbose exit [ 1, true ]
```

**Comment by working-name** [comment]
Maybe implement a check for nodejs version and puke an error about it? That was my issue.

**Comment by daniellockyer** [comment]
The debug log is useful for when users report issues, but I believe it's also the default output in NPM. You should be able to provide `--silent` to `npm` to silence it 🙂
