### ISSUE TITLE
Sqlite3 not compatible with Apple Silicon ARM64 Electron build version 11.0.0-beta.20

### ISSUE THREAD

**Issue by ahmadwaliesipick** [TryGhost/node-sqlite3#1396]
After running app the below message shown. Anyone has solution for this issue?

`Uncaught Exception:
Error: dlopen(/todo-xplat/dist-app/mac-arm64/Todo Cloud.app/Contents/Resources/app.asar.unpacked/node_modules/todo-api/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node, 1): no suitable image found.  Did find:
/project/todo-xplat/dist-app/mac-arm64/Todo Cloud.app/Contents/Resources/app.asar.unpacked/node_modules/todo-api/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node: mach-o, but wrong architecture
/project/todo-xplat/dist-app/mac-arm64/Todo Cloud.app/Contents/Resources/app.asar.unpacked/node_modules/todo-api/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node: mach-o, but wrong architecture
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/project/todo-xplat/dist-app/mac-arm64/Todo Cloud.app/Contents/Resources/app.asar/node_modules/todo-api/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/project/todo-xplat/dist-app/mac-arm64/Todo Cloud.app/Contents/Resources/app.asar/node_modules/todo-api/node_modules/sqlite3/lib/sqlite3.js:2:15)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/project/todo-xplat/dist-app/mac-arm64/Todo Cloud.app/Contents/Resources/app.asar/node_modules/todo-api/node_modules/any-db-sqlite3/index.js:3:20)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at getAdapter (/project/todo-xplat/dist-app/mac-arm64/Todo Cloud.app/Contents/Resources/app.asar/node_modules/todo-api/node_modules/any-db/index.js:27:10)
at Object.connect [as createConnection] (/project/todo-xplat/dist-app/mac-arm64/Todo Cloud.app/Contents/Resources/app.asar/node_modules/todo-api/node_modules/any-db/index.js:14:17)`

**Comment by ahmadwaliesipick** [comment]
```
 lipo -archs  dist-app/mac-arm64/Todo\ Cloud.app/Contents/Resources/app.asar.unpacked/node_modules/todo-api/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node 

x86_64
```

**Comment by daniellockyer** [comment]
Would you be able to try with the latest version - v5.0.3? 🙂
