### ISSUE TITLE
Error: ENOENT: no such file or directory, rename 'build' -> 'build-tmp-napi-v3'

### ISSUE THREAD

**Issue by mailtoamirjohn** [TryGhost/node-sqlite3#1586]
```
C:\Users\johna4\Documents\GitHub\sis-mobile1\electron>npm install sqlite3@5.0.2 ^ --build-from-source ^ --sqlite_libname=sqlcipher-static ^ --sqlite="%CD%\sqlcipher" ^ --runtime=electron ^ --target=10.1.4 ^ --dist-url=https://electronjs.org/headers --verbose

npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'sqlite3@5.0.2',
npm verb cli   '--build-from-source',
npm verb cli   '--sqlite_libname=sqlcipher-static',
npm verb cli   '--sqlite=C:\\Users\\johna4\\Documents\\GitHub\\sis-mobile1\\electron\\sqlcipher',
npm verb cli   '--runtime=electron',
npm verb cli   '--target=10.1.4',
npm verb cli   '--dist-url=https://electronjs.org/headers',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.8
npm info using node@v14.15.0
npm verb npm-session 2d9e74ceeb80ad07
npm http fetch GET 200 https://registry.npmjs.org/sqlite3 22ms (from cache)
npm timing stage:loadCurrentTree Completed in 1390ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 8ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 643ms
npm http fetch GET 200 https://registry.npmjs.org/node-pre-gyp 13ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/node-gyp 19ms (from cache)
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm http fetch GET 200 https://registry.npmjs.org/fstream 96ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/semver 97ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/which 102ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rimraf 670ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 693ms (from cache)
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm http fetch GET 304 https://registry.npmjs.org/osenv 718ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nopt 732ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/abbrev 6ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/os-homedir 131ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/os-tmpdir 157ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/block-stream 6ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/needle 16ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npm-packlist 135ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/debug 7ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/iconv-lite 12ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ms 138ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npm-bundled 135ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npm-normalize-package-bin 160ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ignore-walk 389ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/fs-minipass 22ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 139ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/safe-buffer 149ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 167ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 183ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2750ms
npm timing stage:loadIdealTree Completed in 3613ms
npm timing stage:generateActionsToTake Completed in 70ms
npm verb correctMkdir C:\Users\johna4\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\johna4\AppData\Roaming\npm-cache\_locks\staging-6284d509fdadd3d7.lock for C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\.staging
npm timing action:extract Completed in 255ms
npm timing action:finalize Completed in 88ms
npm timing action:refresh-package-json Completed in 46ms
npm info lifecycle sqlite3@5.0.2~preinstall: sqlite3@5.0.2
npm timing action:preinstall Completed in 4ms
npm info linkStuff sqlite3@5.0.2
npm timing action:build Completed in 3ms
npm info lifecycle sqlite3@5.0.2~install: sqlite3@5.0.2

> sqlite3@5.0.2 install C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\johna4\\Documents\\GitHub\\sis-mobile1\\electron\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.15.0 | win32 | x64
node-pre-gyp verb command install [ 'napi_build_version=3' ]
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info build requesting source compile
node-pre-gyp verb command build [ 'rebuild', 'napi_build_version=3' ]
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: ENOENT: no such file or directory, rename 'build' -> 'build-tmp-napi-v3'
node-pre-gyp ERR! stack     at Object.renameSync (fs.js:772:3)
node-pre-gyp ERR! stack     at Object.module.exports.swap_build_dir_out (C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\node-pre-gyp\lib\util\napi.js:171:6)
node-pre-gyp ERR! stack     at C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\node-pre-gyp\lib\configure.js:46:26
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\node-pre-gyp\lib\util\compile.js:85:9)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19044
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\johna4\\Documents\\GitHub\\sis-mobile1\\electron\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm verb lifecycle sqlite3@5.0.2~install: unsafe-perm in lifecycle true
npm verb lifecycle sqlite3@5.0.2~install: PATH: C:\Users\johna4\AppData\Roaming\nvm\v14.15.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\sqlite3\node_modules\.bin;C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\.bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\johna4\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\dotnet\;C:\Users\johna4\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\johna4\AppData\Local\Programs\Python\Python310\;C:\Users\johna4\.windows-build-tools\python27\;C:\Users\johna4\.windows-build-tools\python27\;C:\Users\johna4\AppData\Roaming\nvm\v14.15.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Program Files\nodejs\node_modules\windows-build-tools\node_modules\.bin;C:\Program Files\nodejs\node_modules\.bin;C:\Users\johna4\AppData\Local\Microsoft\WindowsApps;C:\Users\johna4\AppData\Roaming\npm;C:\Users\johna4\AppData\Local\GitHubDesktop\bin;C:\Users\johna4\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin;C:\Users\johna4\.dotnet\tools
npm verb lifecycle sqlite3@5.0.2~install: CWD: C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\sqlite3
npm timing audit submit Completed in 4273ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 4273ms
npm timing audit body Completed in 1ms
npm info lifecycle sqlite3@5.0.2~install: Failed to exec install script
npm timing action:install Completed in 5677ms
npm verb unlock done using C:\Users\johna4\AppData\Roaming\npm-cache\_locks\staging-6284d509fdadd3d7.lock for C:\Users\johna4\Documents\GitHub\sis-mobile1\electron\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 97ms
npm timing stage:runTopLevelLifecycles Completed in 11509ms
npm WARN SIS2GO@1.2.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iconv-corefoundation@1.1.7 (node_modules\iconv-corefoundation):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for iconv-corefoundation@1.1.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dmg-license@1.0.11 (node_modules\dmg-license):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for dmg-license@1.0.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: sqlite3@5.0.2 install: `node-pre-gyp install --fallback-to-build`
npm verb stack Exit status 7
npm verb stack     at EventEmitter.<anonymous> (C:\Users\johna4\AppData\Roaming\nvm\v14.15.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\johna4\AppData\Roaming\nvm\v14.15.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid sqlite3@5.0.2
npm verb cwd C:\Users\johna4\Documents\GitHub\sis-mobile1\electron
npm verb Windows_NT 10.0.19044
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3@5.0.2" "--build-from-source" "--sqlite_libname=sqlcipher-static" "--sqlite=C:\\Users\\johna4\\Documents\\GitHub\\sis-mobile1\\electron\\sqlcipher" "--runtime=electron" "--target=10.1.4" "--dist-url=https://electronjs.org/headers" "--verbose"
npm verb node v14.15.0
npm verb npm  v6.14.8
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! sqlite3@5.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the sqlite3@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 7, true ]
npm timing npm Completed in 13113ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johna4\AppData\Roaming\npm-cache\_logs\2022-04-22T02_40_23_020Z-debug.log

C:\Users\johna4\Documents\GitHub\sis-mobile1\electron>
```

**Comment by daniellockyer** [comment]
Hey @mailtoamirjohn, can you try with the latest version - v5.0.5? 🙂
