### ISSUE TITLE
Cannot build on FreeBSD

### ISSUE THREAD

**Issue by draga79** [TryGhost/node-sqlite3#1592]
Hello,
trying to install on a FreeBSD jail. Last time I tried (some weeks ago) everything was working, now it fails: 

```
npm install sqlite3

[...]
npm ERR! gyp info using node@14.18.1 | freebsd | x64
npm ERR! gyp info spawn gmake
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from <built-in>:1:
npm ERR! ./../src/gcc-preinclude.h:5:10: fatal error: 'features.h' file not found
npm ERR! #include <features.h>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! gmake: *** [deps/sqlite3.target.mk:143: Release/obj.target/sqlite3/gen/sqlite-autoconf-3380200/sqlite3.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `gmake` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
npm ERR! gyp ERR! System FreeBSD 13.0-RELEASE-p11
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
npm ERR! gyp ERR! cwd /root/node_modules/@louislam/sqlite3
npm ERR! gyp ERR! node -v v14.18.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/node_modules/@louislam/sqlite3/lib/binding/napi-v6-freebsd-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
npm ERR! node-pre-gyp ERR! System FreeBSD 13.0-RELEASE-p11
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/root/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /root/node_modules/@louislam/sqlite3
npm ERR! node-pre-gyp ERR! node -v v14.18.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok

```

Same with: `npm install https://github.com/tryghost/node-sqlite3/tarball/master`

OS is FreeBSD 13.0, arch is amd64.

Thank you.

**Comment by daniellockyer** [comment]
Hey @draga79, we had the same thing reported in the last version but that was fixed in v5.0.5. Are you use you're using `master`/the latest version?

It was reported fixed here: https://github.com/TryGhost/node-sqlite3/issues/1584#issuecomment-1105848463
