### ISSUE TITLE
Cause an Segmentation fault (core dumped) on Node 5.0.7

### ISSUE THREAD

**Issue by vit1251** [TryGhost/node-sqlite3#1605]
### Issue Summary

I execute `node example.js` and cause Segmentation fault with next stacktrace:

```
(gdb) bt
#0  0x00007f4af0650fd6 in node_sqlite3::Statement::RowToJS(Napi::Env, std::vector<node_sqlite3::Values::Field*, std::allocator<node_sqlite3::Values::Field*> >*, std::vector<Napi::String, std::allocator<Napi::String> >) ()
   from /home/vsedyshev/Work/IPS-3288/check/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node
#1  0x00007f4af0653ff4 in node_sqlite3::Statement::AsyncEach(uv_async_s*) ()
   from /home/vsedyshev/Work/IPS-3288/check/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node
#2  0x0000000001564936 in uv__async_io (loop=0x4a43c60 <default_loop_struct>, w=<optimized out>, events=<optimized out>) at ../deps/uv/src/unix/async.c:163
#3  0x0000000001577064 in uv__io_poll (loop=loop@entry=0x4a43c60 <default_loop_struct>, timeout=<optimized out>) at ../deps/uv/src/unix/epoll.c:374
#4  0x0000000001565288 in uv_run (loop=0x4a43c60 <default_loop_struct>, mode=UV_RUN_DEFAULT) at ../deps/uv/src/unix/core.c:389
#5  0x0000000000a43dd5 in node::SpinEventLoop(node::Environment*) ()
#6  0x0000000000b4bdb6 in node::NodeMainInstance::Run(node::EnvSerializeInfo const*) ()
#7  0x0000000000acd592 in node::Start(int, char**) ()
#8  0x00007f4af382609b in __libc_start_main (main=0xa3deb0 <main>, argc=2, argv=0x7ffeadabbc88, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffeadabbc78) at ../csu/libc-start.c:308
#9  0x0000000000a4067c in _start ()
```

### Steps to Reproduce

SELECT * FROM table (with over 10_000 records)

### Version

5.0.7

### Node.js Version

v16.15.0

### How did you install the library?

npm i and npm i --source. ..

**Comment by daniellockyer** [comment]
Thanks for the report 🙂 I'm going to revert the commit that caused this until further investigation can be done: https://github.com/TryGhost/node-sqlite3/commit/5063367567fd1abe47bafc2095fb4f9090a260e3
