### ISSUE TITLE
WSL2 - VSCODE - napi issue/question

### ISSUE THREAD

**Issue by ben-w-smith** [TryGhost/node-sqlite3#1609]
### Issue Summary

I ran into an issue that might be a knowledge gap on my end but wanted to provide some notes in case it helps someone else.

I'm on Windows 10 machine, running WSL2 with Ubuntu 20.04. 

I installed sqlite3 via:
npm install sqlite3

I could execute scripts in the WSL2 terminal but kept receiving an error when attempting to "Run and Debug" in VSCode.

I would receive the following error - included in relevant logs/output section, bold emphasis is mine.

Solution:
I found that by installing sqlite3 on the windows host machine I could move the directory node_modules/sqlite3/binding/**napi-v6-win32-unknown-x64** into the WSL2 project's node_modules/sqlite3/lib/binding directory I was able to "Run and Debug" in VSCode.

Request:
Is there a cli command to force the installation of this binding for windows?

### Relevant logs or output

```
(node:1576) UnhandledPromiseRejectionWarning: Error: Cannot find module 'c:\...\node_modules\sqlite3\lib\binding\**napi-v6-win32-unknown-x64**\node_sqlite3.node'
Require stack:
- c:\...\node_modules\sqlite3\lib\sqlite3-binding.js
- c:\...\node_modules\sqlite3\lib\sqlite3.js
- c:\...\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (c:\...\node_modules\sqlite3\lib\sqlite3-binding.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
<node_internals>/internal/process/warning.js:32
(node:1576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
<node_internals>/internal/process/warning.js:32
(node:1576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

### Version

5.0.8

### Node.js Version

16.15.0

### How did you install the library?

npm install sqlite3

**Comment by BobbyWibowo** [comment]
It sounds like you're running the project with a Windows-installed Node binary, or at least your Vscode determined that it should do so

If the project is indeed properly supposed to run on a Linux/WSL environment, your Vscode should be using the Linux-installed Node binary, and thus cause sqlite3 to properly use Linux binding

---

![image](https://user-images.githubusercontent.com/9364930/170141531-f8d12ab6-ae07-4c30-ae5d-ba11f56177c6.png)
By having `"console": "integratedTerminal"` in `launch.json`, I can see the full command Vscode runs when doing Run & Debug action

![image](https://user-images.githubusercontent.com/9364930/170141615-4a604336-2182-4f0d-bc59-da5c0d76601b.png)
The only sqlite3 binding installed in my project

**Comment by ljcucc** [comment]
I have same / similar issue when I tried to import package on code sandbox's environment (iOS) ( which having weird arch info )
```
node-pre-gypError: Cannot find module '/private/var/mobile/Containers/Data/Application/.../node_modules/sqlite3/lib/binding/napi-v3-ios-unknown-arm64/node_sqlite3.node'
Require stack:
- /private/var/mobile/Containers/Data/Application/.../node_modules/sqlite3/lib/sqlite3-binding.js
- /private/var/mobile/Containers/Data/Application/.../node_modules/sqlite3/lib/sqlite3.js
- /private/var/mobile/Containers/Data/Application/.../server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:984:15)
    at Function.Module._load (internal/modules/cjs/loader.js:866:27)
    at Module.require (internal/modules/cjs/loader.js:1051:19)
    at require (internal/modules/cjs/helpers.js:86:18)
    at Object.<anonymous> (/private/var/mobile/Containers/Data/Application/.../node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1009:32)
    at Function.Module._load (internal/modules/cjs/loader.js:903:14)
    at Module.require (internal/modules/cjs/loader.js:1051:19)
```

version: `"sqlite3": "^5.0.8"`

Isn't v5+ already supported Node-API ?

**Comment by daniellockyer** [comment]
This appears to be a configuration issue with VSCode - please ensure the environment you're running sqlite3 under is the one you expect 🙂
