### ISSUE TITLE
 `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by TeemuHokkane** [TryGhost/node-sqlite3#1610]
### Issue Summary

Operating system:
Red Hat Enterprise 4.8.5-44

I have been developing my application on windows 10/11 environments without issues.
Today I copied my project to my server hosted with cPanel and started setting it up for test deployment.
I ran npm install without issues (sqlite3 installed without issues)
Everything was looking good until I tried to start the application, then it crashed and I got the error logs below.

As far as I understand the issue seems to be coming from knex trying to install sqlite. 

Issue #1582 seems to have same error message

I'm not completely sure if this is the right repo for this issue, let me know if I should be making this to knex repo

### Relevant logs or output

Knex: run
$ npm install sqlite3 --save
/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/c3hep37e/nodevenv/App/16/lib/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/c3hep37e/nodevenv/App/16/lib/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/c3hep37e/nodevenv/App/16/lib/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
/home/c3hep37e/nodevenv/App/16/lib/node_modules/knex/lib/client.js:194
      throw new Error(`${message}\n${e.message}`);
      ^

Error: Knex: run
$ npm install sqlite3 --save
/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/c3hep37e/nodevenv/App/16/lib/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
    at Client_SQLite3.initializeDriver (/home/c3hep37e/nodevenv/App/16/lib/node_modules/knex/lib/client.js:194:13)
    at new Client (/home/c3hep37e/nodevenv/App/16/lib/node_modules/knex/lib/client.js:75:12)
    at new Client_SQLite3 (/home/c3hep37e/nodevenv/App/16/lib/node_modules/knex/lib/dialects/sqlite3/index.js:22:5)
    at Function.knex (/home/c3hep37e/nodevenv/App/16/lib/node_modules/knex/lib/knex-builder/Knex.js:12:28)
    at Object.<anonymous> (/home/c3hep37e/App/ApiRoutes.js:12:28)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

### Version

5.0.8

### Node.js Version

16.15.0

### How did you install the library?

npm install sqlite3

**Comment by HirenPatel2791** [comment]
I am seeing the same error on jenkins with version 5.0.8, any solution?

**Comment by TeemuHokkane** [comment]
> I am seeing the same error on jenkins with version 5.0.8, any solution?

For me solution was using 5.0.2

**Comment by heikkipora** [comment]
@TeemuHokkane see https://github.com/TryGhost/node-sqlite3/issues/1582

**Comment by yizhiyan** [comment]
use 5.0.2
and update gcc
```
sudo yum install centos-release-scl
sudo yum install devtoolset-8-gcc*
scl enable devtoolset-8 bash
```

**Comment by YassenCarti** [comment]
just use v5.0.2

`npm uninstall sqlite3`
`npm install sqlite3@5.0.2`
