### ISSUE TITLE
SQLite3 shows unsupported Architecture.

### ISSUE THREAD

**Issue by saroj990** [TryGhost/node-sqlite3#1618]
### Issue Summary:
Unable to build SQLite3 on intel Mac OSx.

I am trying build an electron app with SQLite3 as dependency, but each time I do `yarn`, it ends up with a fail with unsupported architecture error. Tried it with different versions of `Node` and `SQLite3`,  but it didn't work either.

Here is the pacakge.json file
```
{
  "name": "neetoseoaudit",
  "version": "0.1.9",
  "private": true,
  "dependencies": {
    "@bigbinary/neeto-icons": "^1.8.29",
    "@bigbinary/neetoui": "^3.2.10",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "autoprefixer": "^10.0.1",
    "cheerio": "^1.0.0-rc.3",
    "classnames": "^2.3.1",
    "concurrently": "^5.3.0",
    "electron": "^16.0.1",
    "file-saver": "^2.0.5",
    "formik": "^2.2.9",
    "node-sass": "^6.0.1",
    "path": "^0.12.7",
    "postcss-cli": "^8.1.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.2",
    "react-router-dom": "^6.2.1",
    "react-router-nav-prompt": "^0.4.1",
    "react-scripts": "^4.0.3",
    "react-toastify": "^8.1.0",
    "react-virtualized-auto-sizer": "^1.0.5",
    "react-window": "^1.8.6",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "remixicon": "^2.5.0",
    "simplecrawler": "^1.1.9",
    "sqlite3": "^5.0.2n",
    "use-timer": "^2.0.1",
    "wait-on": "^5.2.0",
    "xlsx": "^0.17.4"
  },
  "main": "main.js",
  "homepage": "./",
  "scripts": {
    "build:style": "tailwind build src/styles/main.css -o src/styles/tailwind.css",
    "start": "yarn run build:style && react-scripts start",
    "build": "yarn run build:style && react-scripts build",
    "postinstall": "electron-builder install-app-deps --arch arm64",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "electron": "concurrently \"BROWSER=none yarn start\" \"wait-on http://localhost:3000 && electron .\"",
    "package-mac": "yarn build && electron-packager . neetoseoaudit --overwrite --platform=darwin --arch=x64  --prune=true --out=release-builds",
    "package-win": "yarn build && electron-packager . neetoseoaudit --asar --overwrite --platform=win32 --arch=x64  --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"neetoseoaudit\""
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "electron-builder": "^22.14.5",
    "electron-devtools-installer": "^3.1.1",
    "electron-packager": "^15.2.0",
    "husky": "^4.3.0",
    "lint-staged": "^10.4.0",
    "prettier": "^2.1.2",
    "tailwindcss": "^1.9.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,jsx,json,css,scss,md}": [
      "prettier --write"
    ]
  }
}

```

### Relevant logs or output

```
yarn install v1.22.19
warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @bigbinary/neetoui@3.2.10" has incorrect peer dependency "react@^16.13.1".
warning " > @bigbinary/neetoui@3.2.10" has incorrect peer dependency "react-dom@^16.13.1".
warning " > @bigbinary/neetoui@3.2.10" has incorrect peer dependency "react-router-dom@^5.2.0".
warning "@bigbinary/neetoui > raw-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > react-router-nav-prompt@0.4.1" has incorrect peer dependency "react@^16.13.1".
warning " > react-router-nav-prompt@0.4.1" has incorrect peer dependency "react-router-dom@^5.2.0".
warning "@bigbinary/neetoui > react-outside-click-handler > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning " > autoprefixer@10.1.0" has unmet peer dependency "postcss@^8.1.0".
warning " > postcss-cli@8.3.1" has unmet peer dependency "postcss@^8.0.0".
warning "postcss-cli > postcss-reporter@7.0.2" has unmet peer dependency "postcss@^8.1.0".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "react-scripts > eslint-plugin-testing-library > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.18.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps --arch arm64
  • electron-builder  version=22.14.13
  • public/electron.js not found. Please see https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3
  • loaded parent configuration  preset=react-cra
  • rebuilding native dependencies  dependencies=node-sass@6.0.1, sqlite3@5.0.8, fsevents@1.2.13 platform=darwin arch=arm64
  • rebuilding native dependency  name=sqlite3 version=5.0.8
  • rebuilding native dependency  name=node-sass version=6.0.1
  • rebuilding native dependency  name=fsevents version=1.2.13
  ⨯ cannot execute  cause=exit status 1
yarn run v1.22.19
$ node-pre-gyp install --fallback-to-build
      CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
      LIBTOOL-STATIC Release/nothing.a
      ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3380400/sqlite3.c
      TOUCH Release/obj.target/deps/action_before_build.stamp
      CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3380400/sqlite3.o
    Failed to execute '/Users/sarojsasamal/.nvm/versions/node/v14.15.0/bin/node /Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
warning ../../../../../package.json: No license field
    node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@1.0.9
    node-pre-gyp info using node@14.15.0 | darwin | x64
    node-pre-gyp http GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.8/napi-v6-darwin-unknown-arm64.tar.gz
    node-pre-gyp ERR! install response status 404 Not Found on https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.8/napi-v6-darwin-unknown-arm64.tar.gz 
    node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.8 and electron@16.0.1 (electron-v16.0 ABI, unknown) (falling back to source compile with node-gyp) 
    node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.8/napi-v6-darwin-unknown-arm64.tar.gz 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@8.4.1
    gyp info using node@14.15.0 | darwin | x64
    gyp info ok 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@8.4.1
    gyp info using node@14.15.0 | darwin | x64
    gyp info find Python using Python version 3.9.13 found at "/usr/local/opt/python@3.9/bin/python3.9"
    gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
    gyp info spawn args [
    gyp info spawn args   '/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/sarojsasamal/.electron-gyp/16.0.1/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/sarojsasamal/.electron-gyp/16.0.1',
    gyp info spawn args   '-Dnode_gyp_dir=/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/Users/sarojsasamal/.electron-gyp/16.0.1/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info ok 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@8.4.1
    gyp info using node@14.15.0 | darwin | x64
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
    In file included from Release/obj/gen/sqlite-autoconf-3380400/sqlite3.c:14014:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:68:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
    #error Unsupported architecture
     ^
    In file included from Release/obj/gen/sqlite-autoconf-3380400/sqlite3.c:14014:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:33:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from Release/obj/gen/sqlite-autoconf-3380400/sqlite3.c:14014:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_dev_t;         /* dev_t */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
    typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
    typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
    typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
            ^
    note: '__uint128_t' declared here
    In file included from Release/obj/gen/sqlite-autoconf-3380400/sqlite3.c:14014:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_wctype_t;
            ^
    note: '__uint128_t' declared here
    In file included from Release/obj/gen/sqlite-autoconf-3380400/sqlite3.c:14014:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from Release/obj/gen/sqlite-autoconf-3380400/sqlite3.c:14014:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:32:9: error: unknown type name '__darwin_va_list'
    typedef __darwin_va_list va_list;
            ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3380400/sqlite3.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    gyp ERR! System Darwin 19.6.0
    gyp ERR! command "/Users/sarojsasamal/.nvm/versions/node/v14.15.0/bin/node" "/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
    gyp ERR! cwd /Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3
    gyp ERR! node -v v14.15.0
    gyp ERR! node-gyp -v v8.4.1
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/Users/sarojsasamal/.nvm/versions/node/v14.15.0/bin/node /Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    node-pre-gyp ERR! System Darwin 19.6.0
    node-pre-gyp ERR! command "/Users/sarojsasamal/.nvm/versions/node/v14.15.0/bin/node" "/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3
    node-pre-gyp ERR! node -v v14.15.0
    node-pre-gyp ERR! node-pre-gyp -v v1.0.9
    node-pre-gyp ERR! not ok 
error Command failed with exit code 1.
    
                    command=/Users/sarojsasamal/.nvm/versions/node/v14.15.0/bin/node /Users/sarojsasamal/.nvm/versions/node/v14.15.0/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/Users/sarojsasamal/Projects/BigBinary/neeto-seoaudit/node_modules/sqlite3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Version

5.0.2

### Node.js Version

14.15.0

### How did you install the library?

macOs Catalina Version 10.15.7
Yarn add  sqlite3

**Comment by mjovanc** [comment]
I'm experiencing the same issue I have tried both with Node 14 and 18. I tried specifying:

`npm install sqlite3 --build-from-source --target_arch=arm64 --fallback-to-build`

But however it does not work. Using sqlite3 version 5.0.8

**Comment by saroj990** [comment]
@mjovanc have you tried `npm install sqlite3 --build-from-source` command ?

**Comment by mjovanc** [comment]
@saroj990 Yes, still the same issue unfortunately.

**Comment by michelgokan** [comment]
@saroj990 I have the exact same problem on an M1 Pro machine after running `npm install sqlite3@5.0.8`:

`npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.8/napi-v6-darwin-unknown-arm64.tar.gz`

**Comment by michelgokan** [comment]
When trying to build from the source:

`Release/obj/gen/sqlite-autoconf-3380400/sqlite3.c:341:10: fatal error: cannot open file '/usr/local/include/stdarg.h': Permission denied`

**Comment by michelgokan** [comment]
Okay using x64 version fixed the problem for now: 

`npm install sqlite3 --target_arch=x64`

**Comment by michelgokan** [comment]
@saroj990 I believe this should be re-opened
