### ISSUE TITLE
Unable to  install on arch mips64

### ISSUE THREAD

**Issue by ColonelDarcy2018** [TryGhost/node-sqlite3#1623]
### Issue Summary

Unable to  install on arch mips64:
```
node-pre-gyp info check checked for "/home/user/rpa-app/rpa-robot/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-mips64el/node_sqlite3.node" (not found)

Build from source failed either:
ENOENT: no such file or directory, rename 'build' -> 'build-tmp-napi-v6'
```

### Relevant logs or output

```
user@user-PC:rpa-app/rpa-robot$ npm install sqlite3 --loglevel=info --ignore-optional
npm info it worked if it ends with ok
npm info using npm@6.14.16
npm info using node@v14.19.1
......
npm info lifecycle sqlite3@5.0.8 install: sqlite3@5.0.8

> sqlite3@5.0.8 install /home/user/rpa-app/rpa-robot/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@14.19.1 | linux | mips64el
node-pre-gyp info check checked for "/home/user/rpa-app/rpa-robot/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-mips64el/node_sqlite3.node" (not found)
node-pre-gyp http GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.8/napi-v6-linux-glibc-mips64el.tar.gz
Floating point exception
npm info lifecycle sqlite3@5.0.8install: Failed to exec install script
npm timing action:install Completed in 1563ms
npm timing stage:rollbackFailedOptional Completed in 449ms
npm timing stage:runTopLevelLifecycles Completed in 69061ms
npm WARN dva-loading@3.0.22 requires a peer of dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-erb@0.0.2 requires a peer of eslint-config-prettier@^3.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-erb@0.0.2 requires a peer of eslint-import-resolver-webpack@^0.10.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-erb@0.0.2 requires a peer of eslint-plugin-compat@^2.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-erb@0.0.2 requires a peer of eslint-plugin-jsx-a11y@6.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of @typescript-eslint/eslint-plugin@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of @typescript-eslint/parser@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of eslint@6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@13.0.1 requires a peer of eslint@>=6.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard-jsx@7.0.0 requires a peer of eslint@>=6.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-umi@1.6.0 requires a peer of eslint-plugin-flowtype@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-umi@1.6.0 requires a peer of eslint-plugin-react-hooks@1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN io-ts@2.2.16 requires a peer of fp-ts@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN io-ts-types@0.5.16 requires a peer of fp-ts@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN monocle-ts@2.3.13 requires a peer of fp-ts@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN newtype-ts@0.3.5 requires a peer of fp-ts@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN com.sz.rpa.robot@5.8.4 No repository field.
npm WARN com.sz.rpa.robot@5.8.4 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"mips64el"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"mips64el"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"mips64el"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"mips64el"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-chromedriver@6.0.0 (node_modules/electron-chromedriver):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-chromedriver@6.0.0 install: `node ./download-chromedriver.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 136
npm ERR! sqlite3@5.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 136
npm ERR! 
npm ERR! Failed at the sqlite3@5.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 77038ms
```

-------------------------------

It's looks like napi-v6-linux-glibc-mips64el.tar.gz doesn't exists,so I also tried:

```
user@user-PC:/node-sqlite3-5.0.8$ npm install --build-from-source --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--build-from-source',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.16
npm info using node@v14.19.1
npm verb npm-session 596d0a6a1625440d
npm info lifecycle sqlite3@5.0.8 preinstall: sqlite3@5.0.8
npm timing stage:loadCurrentTree Completed in 2009ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 13ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 502ms
npm http fetch GET 200 http://10.4.2.21:8081/repository/npm-group/js-yaml 1039ms
npm http fetch GET 200 http://10.4.2.21:8081/repository/npm-group/fsevents 376ms
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2589ms
npm timing stage:loadIdealTree Completed in 3552ms
npm timing stage:generateActionsToTake Completed in 135ms
npm verb correctMkdir /home/user/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/user/.npm/_locks/staging-875a9d0b2e1d5236.lock for /home/user/node-sqlite3-5.0.8/node_modules/.staging
npm http fetch POST 400 http://10.4.2.21:8081/repository/npm-group/-/npm/v1/security/audits/quick 110ms
npm timing action:extract Completed in 133ms
npm info lifecycle js-yaml@3.14.1 preuninstall: js-yaml@3.14.1
npm info lifecycle js-yaml@3.14.1 uninstall: js-yaml@3.14.1
npm verb unbuild rmStuff js-yaml@3.14.1 from /home/user/node-sqlite3-5.0.8/node_modules
npm info lifecycle js-yaml@3.14.1 postuninstall: js-yaml@3.14.1
npm info lifecycle undefined preuninstall: undefined
npm info lifecycle undefined uninstall: undefined
npm verb unbuild rmStuff undefined from /home/user/node-sqlite3-5.0.8/node_modules
npm verb unbuild rmStuff in /home/user/node-sqlite3-5.0.8/node_modules/eslint/node_modules
npm info lifecycle undefined postuninstall: undefined
npm timing action:unbuild Completed in 33ms
npm timing action:remove Completed in 40ms
npm timing action:finalize Completed in 10ms
npm timing action:refresh-package-json Completed in 17ms
npm info lifecycle js-yaml@3.14.1 preinstall: js-yaml@3.14.1
npm timing action:preinstall Completed in 1ms
npm info linkStuff js-yaml@3.14.1
npm verb linkBins [
npm verb linkBins   { 'js-yaml': 'bin/js-yaml.js' },
npm verb linkBins   '/home/user/node-sqlite3-5.0.8/node_modules/eslint/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm timing action:build Completed in 18ms
npm info lifecycle js-yaml@3.14.1 install: js-yaml@3.14.1
npm timing action:install Completed in 2ms
npm info lifecycle js-yaml@3.14.1 postinstall: js-yaml@3.14.1
npm timing action:postinstall Completed in 1ms
npm verb unlock done using /home/user/.npm/_locks/staging-875a9d0b2e1d5236.lock for /home/user/node-sqlite3-5.0.8/node_modules/.staging
npm timing stage:executeActions Completed in 312ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm info linkStuff sqlite3@5.0.8
npm info lifecycle sqlite3@5.0.8 install: sqlite3@5.0.8

> sqlite3@5.0.8 install /home/user/node-sqlite3-5.0.8
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   '/usr/local/bin/node',
node-pre-gyp verb cli   '/home/user/node-sqlite3-5.0.8/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@14.19.1 | linux | mips64el
node-pre-gyp verb command install [ 'napi_build_version=6' ]
node-pre-gyp info build requesting source compile
node-pre-gyp verb command build [ 'rebuild', 'napi_build_version=6' ]
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'clean'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.19.1 | linux | mips64el
gyp verb command clean []
gyp verb clean removing "build" directory
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=/home/user/node-sqlite3-5.0.8/lib/binding/napi-v6-linux-glibc-mips64el/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/home/user/node-sqlite3-5.0.8/lib/binding/napi-v6-linux-glibc-mips64el',
gyp verb cli   '--napi_version=8',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=6',
gyp verb cli   '--node_napi_label=napi-v6'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.19.1 | linux | mips64el
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/bin/python"
gyp verb find Python - executing "/usr/bin/python" to get version
gyp verb find Python - version is "2.7.16"
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp verb get node dir no --target version specified, falling back to host node version: 14.19.1
gyp verb command install [ '14.19.1' ]
gyp verb install input version string "14.19.1"
gyp verb install installing version: 14.19.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 0
gyp verb needs "installVersion" 9
gyp verb install version is no good; reinstalling
gyp verb ensuring nodedir is created /home/user/.cache/node-gyp/14.19.1
gyp http GET https://nodejs.org/download/release/v14.19.1/node-v14.19.1-headers.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: ENOENT: no such file or directory, rename 'build' -> 'build-tmp-napi-v6'
node-pre-gyp ERR! stack     at Object.renameSync (fs.js:797:3)
node-pre-gyp ERR! stack     at Object.module.exports.swap_build_dir_out (/home/user/node-sqlite3-5.0.8/node_modules/@mapbox/node-pre-gyp/lib/util/napi.js:171:8)
node-pre-gyp ERR! stack     at /home/user/node-sqlite3-5.0.8/node_modules/@mapbox/node-pre-gyp/lib/configure.js:46:16
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/node-sqlite3-5.0.8/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:91:5)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Linux 4.19.0-loongson-3-desktop
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/user/node-sqlite3-5.0.8/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/user/node-sqlite3-5.0.8
node-pre-gyp ERR! node -v v14.19.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm verb lifecycle sqlite3@5.0.8 install: unsafe-perm in lifecycle true
npm verb lifecycle sqlite3@5.0.8 install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/node-sqlite3-5.0.8/node_modules/.bin:/usr/local/go1.17.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin
npm verb lifecycle sqlite3@5.0.8 install: CWD: /home/user/node-sqlite3-5.0.8
npm info lifecycle sqlite3@5.0.8 install: Failed to exec install script
npm verb stack Error: sqlite3@5.0.8 install: `node-pre-gyp install --fallback-to-build`
npm verb stack Exit status 7
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:400:28)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:400:28)
npm verb stack     at maybeClose (internal/child_process.js:1058:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
npm verb pkgid sqlite3@5.0.8
npm verb cwd /home/user/node-sqlite3-5.0.8
npm verb Linux 4.19.0-loongson-3-desktop
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--build-from-source" "--verbose"
npm verb node v14.19.1
npm verb npm  v6.14.16
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! sqlite3@5.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the sqlite3@5.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 7, true ]
npm timing npm Completed in 9190ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-07-11T02_25_16_212Z-debug.log
```

### Version

5.0.8

### Node.js Version

14.19.1

### How did you install the library?

UnionTech OS GNU/Linux 20  mips64el

**Comment by daniellockyer** [comment]
@ColonelDarcy2018 Would you be able to install Python 3 and try again?

**Comment by daniellockyer** [comment]
Closing as I believe the issue stems from a lack of Python 3 on the system 🙂
