### ISSUE TITLE
I can't install Sqlite3 on my armbian system via npm

### ISSUE THREAD

**Issue by xiaoye-x** [TryGhost/node-sqlite3#1642]
### Issue Summary

I can't install Sqlite3 on my armbian system via npm

`install response status 404 Not Found on https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.2/napi-v6-linux-glibc-arm.tar.gz `

### Relevant logs or output

```
npm ERR! code 1
npm ERR! path /root/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/bin/node /usr/share/nodejs/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@12.22.9 | linux | arm
npm ERR! node-pre-gyp info check checked for "/root/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.2/napi-v6-linux-glibc-arm.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.2/napi-v6-linux-glibc-arm.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.1.2 and node@12.22.9 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.2/napi-v6-linux-glibc-arm.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@12.22.9 | linux | arm
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@12.22.9 | linux | arm
npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/include/nodejs/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@12.22.9 | linux | arm
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/usr/share/nodejs/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /usr/share/nodejs/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/usr/share/nodejs/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /usr/share/nodejs/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/usr/share/nodejs/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /usr/share/nodejs/which/which.js:80:22
npm ERR! gyp ERR! stack     at /usr/share/nodejs/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/share/nodejs/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.15.43-draginohp0z
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/root/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
npm ERR! gyp ERR! cwd /root/node_modules/sqlite3
npm ERR! gyp ERR! node -v v12.22.9
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/share/nodejs/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm ERR! node-pre-gyp ERR! System Linux 5.15.43-draginohp0z
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/root/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /root/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v12.22.9
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-10T02_43_42_027Z-debug-0.log
```

### Version

the latest

### Node.js Version

v12.22.9

### How did you install the library?

npm install sqlite3

Linux dragino-3e1a15 5.15.43-draginohp0z #22.05.2 SMP Fri Sep 30 04:30:14 UTC 2022 armv7l armv7l armv7l GNU/Linux

**Comment by daniellockyer** [comment]
@xiaoye-x Unfortunately we don't currently offer Linux `arm` binaries, so this library has to be compiled - https://github.com/TryGhost/node-sqlite3#prebuilt-binaries

If you look at the error, `npm ERR! gyp ERR! stack Error: not found: make`. You should install `build-essential` or whatever your system provides `make` under
