### ISSUE TITLE
Unknown Runtime: 'electron '

### ISSUE THREAD

**Issue by ncortines** [TryGhost/node-sqlite3#1644]
### Issue Summary

Hi 👋

I'm trying to rebuild the module with sqlcipher support for electron 21.1.0, and I'm getting the error `Unknown Runtime: 'electron '`.

I'm not sure where the problem is. Most likely I'm not doing something properly.

I'd much appreciate if someone could take a look at this logs.

Thanks!

```
[17:02:13] 'build-sqlcipher' errored after 2.49 s
[17:02:13] Error: Command failed: set npm_config_target=21.1.0 && set npm_config_arch=x64 && set npm_config_target_arch=x64 && set npm_config_disturl=https://atom.io/download/electron && set npm_config_runtime=electron && set npm_config_build_from_source=true && npm rebuild sqlite3 --build-from-source --sqlite_libname=sqlite3 --sqlite=C:\Users\paco\acme\my-electron-app\sqlcipher --verbose
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm verb cli C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@8.11.0
npm info using node@v16.16.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 4ms
npm timing config:load:file:C:\Users\paco\AppData\Roaming\nvm\v16.16.0\node_modules\npm\npmrc Completed in 1ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 4ms
npm timing config:load:env Completed in 2ms
npm timing config:load:file:C:\Users\paco\acme\my-electron-app\build-temp\.npmrc Completed in 0ms
npm timing config:load:project Completed in 5ms
npm timing config:load:file:C:\Users\paco\.npmrc Completed in 1ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:C:\Program Files (x86)\nodejs\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 2ms
npm timing config:load Completed in 27ms
npm timing npm:load:configload Completed in 28ms
npm timing npm:load:mkdirpcache Completed in 1ms
npm timing npm:load:mkdirplogs Completed in 1ms
npm verb title npm rebuild sqlite3
npm verb argv "rebuild" "sqlite3" "--build-from-source" "--sqlite_libname" "sqlite3" "--sqlite" "C:\\Users\\paco\\acme\\my-electron-app\\sqlcipher" "--loglevel" "verbose"
npm timing npm:load:setTitle Completed in 5ms
npm timing config:load:flatten Completed in 6ms
npm timing npm:load:display Completed in 12ms
npm verb logfile logs-max:10 dir:C:\Users\paco\AppData\Local\npm-cache\_logs
npm verb logfile C:\Users\paco\AppData\Local\npm-cache\_logs\2022-10-13T15_02_12_690Z-debug-0.log
npm timing npm:load:logFile Completed in 13ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 62ms
npm timing arborist:ctor Completed in 0ms
npm timing build:queue Completed in 0ms
npm info run sqlite3@5.1.2 install node_modules/sqlite3 node-pre-gyp install --fallback-to-build
npm info run sqlite3@5.1.2 install { code: 7, signal: null }
npm timing command:rebuild Completed in 1062ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Users\paco\AppData\Roaming\nvm\v16.16.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:527:28)
npm verb stack     at maybeClose (node:internal/child_process:1092:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb pkgid sqlite3@5.1.2
npm verb cwd C:\Users\paco\acme\my-electron-app\build-temp
npm verb Windows_NT 10.0.22000
npm verb node v16.16.0
npm verb npm  v8.11.0
npm ERR! code 7
npm ERR! path C:\Users\paco\acme\my-electron-app\build-temp\node_modules\sqlite3
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp verb cli [
npm ERR! node-pre-gyp verb cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
npm ERR! node-pre-gyp verb cli   'C:\\Users\\paco\\acme\\my-electron-app\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp',
npm ERR! node-pre-gyp verb cli   'install',
npm ERR! node-pre-gyp verb cli   '--fallback-to-build'
npm ERR! node-pre-gyp verb cli ]
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.16.0 | win32 | x64
npm ERR! node-pre-gyp verb command install [ 'napi_build_version=6' ]
npm ERR! node-pre-gyp info build requesting source compile
npm ERR! node-pre-gyp verb command build [ 'rebuild', 'napi_build_version=6' ]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\paco\\AppData\\Roaming\\nvm\\v16.16.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'clean'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.16.0 | win32 | x64
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp info ok
npm ERR! node-pre-gyp ERR! UNCAUGHT EXCEPTION
npm ERR! node-pre-gyp ERR! stack Error: Unknown Runtime: 'electron '
npm ERR! node-pre-gyp ERR! stack     at get_runtime_abi (C:\Users\paco\acme\my-electron-app\node_modules\@mapbox\node-pre-gyp\lib\util\versioning.js:86:13)
npm ERR! node-pre-gyp ERR! stack     at Object.module.exports.evaluate (C:\Users\paco\acme\my-electron-app\node_modules\@mapbox\node-pre-gyp\lib\util\versioning.js:295:15)
npm ERR! node-pre-gyp ERR! stack     at handle_gyp_opts (C:\Users\paco\acme\my-electron-app\node_modules\@mapbox\node-pre-gyp\lib\util\handle_gyp_opts.js:59:27)
npm ERR! node-pre-gyp ERR! stack     at configure (C:\Users\paco\acme\my-electron-app\node_modules\@mapbox\node-pre-gyp\lib\configure.js:12:3)
npm ERR! node-pre-gyp ERR! stack     at C:\Users\paco\acme\my-electron-app\node_modules\@mapbox\node-pre-gyp\lib\build.js:43:7
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\paco\acme\my-electron-app\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:91:5)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22000
npm ERR! node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\paco\\acme\\my-electron-app\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\paco\acme\my-electron-app\build-temp\node_modules\sqlite3
npm ERR! node-pre-gyp ERR! node -v v16.16.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm verb exit 7
npm timing npm Completed in 1212ms
npm verb unfinished npm timer build 1665673333311
npm verb unfinished npm timer build:deps 1665673333312
npm verb unfinished npm timer build:run:install 1665673333316
npm verb unfinished npm timer build:run:install:node_modules/sqlite3 1665673333316
npm verb code 7

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paco\AppData\Local\npm-cache\_logs\2022-10-13T15_02_12_690Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:537:15)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)

C:\Users\paco\acme\my-electron-app>
```

### Steps to Reproduce

1. Rebuild the module with sqlcipher for electron 21.1.0 using the following command:
```set npm_config_target=21.1.0 && set npm_config_arch=x64 && set npm_config_target_arch=x64 && set npm_config_disturl=https://atom.io/download/electron && set npm_config_runtime=electron && set npm_config_build_from_source=true && npm rebuild sqlite3 --build-from-source --sqlite_libname=sqlite3 --sqlite=C:\Users\paco\acme\my-electron-app\sqlcipher --verbose```

### Version

5.1.2

### Node.js Version

16.16.0

### How did you install the library?

Windows 10 ARM 64 bit

**Comment by ncortines** [comment]
My bad, I have read the docs better and now I'm setting proper flags. Now I'm stuck on a 403 while downloading headers :)
