### ISSUE TITLE
npm install fails when using a private registry

### ISSUE THREAD

**Issue by joshuakb2** [TryGhost/node-sqlite3#1645]
### Issue Summary

In NPM 7 and 8, trying to install the `sqlite3` npm package fails if a custom registry is configured.

Here is NPM's bug: https://github.com/npm/cli/issues/5234

Maybe NPM just needs to fix this, but from that issue it looks like a different package was able to work around the NPM bug. That issue also mentions a workaround that helped me overcome this issue for now.

### Relevant logs or output

`npm install sqlite3` (with private registry configured):
```
npm info run sqlite3@5.1.2 install node_modules/sqlite3 node-gyp rebuild
npm info run sqlite3@5.1.2 install { code: 1, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/home/jbaker/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:527:28)
npm verb stack     at maybeClose (node:internal/child_process:1092:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb pkgid sqlite3@5.1.2
npm verb cwd /home/jbaker/testing
npm verb Linux 5.15.0-48-generic
npm verb node v16.15.0
npm verb npm  v8.19.2
npm ERR! code 1
npm ERR! path /home/jbaker/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/home/jbaker/.nvm/versions/node/v16.15.0/bin/node',
npm ERR! gyp verb cli   '/home/jbaker/node_modules/.bin/node-gyp',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.15.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.10.6"
npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.15.0
npm ERR! gyp verb command install [ '16.15.0' ]
npm ERR! gyp verb install input version string "16.15.0"
npm ERR! gyp verb install installing version: 16.15.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.15.0
npm ERR! gyp verb build dir attempting to create "build" dir: /home/jbaker/node_modules/sqlite3/build
npm ERR! gyp verb build dir "build" dir needed to be created? Yes
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/jbaker/node_modules/sqlite3/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /home/jbaker/node_modules/sqlite3/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/jbaker/node_modules/sqlite3/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/jbaker/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jbaker/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jbaker/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jbaker/.cache/node-gyp/16.15.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/jbaker/.cache/node-gyp/16.15.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/jbaker/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/jbaker/.cache/node-gyp/16.15.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/jbaker/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/jbaker/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.15.0-48-generic
npm ERR! gyp ERR! command "/home/jbaker/.nvm/versions/node/v16.15.0/bin/node" "/home/jbaker/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/jbaker/node_modules/sqlite3
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm verb exit 1
npm verb code 1
```

### Version

5.1.2

### Node.js Version

16.15.0

### How did you install the library?

npm cli in Ubuntu 22.04. Using private npm registry.

**Comment by daniellockyer** [comment]
Please reinstall the latest and try again. We've updated the build system since 5.1.2
