### ISSUE TITLE
Installation failing for electron project

### ISSUE THREAD

**Issue by shadowvzs** [TryGhost/node-sqlite3#1652]
### Issue Summary
OS: ubuntu 64bit

when I try to install it as it was written on the sqlite3 npm page then I get this error 

```yarn workspace @pb/electron add sqlite3 --build-from-source --runtime=electron --target=18.2.1 --dist-url=https://electronjs.org/headers```

### Relevant logs or output

```
$`yarn workspace @pb/electron add sqlite3 --build-from-source --runtime=electron --target=18.2.1 --dist-url=https://electronjs.org/headers

error /home/katalin2/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/katalin2/node_modules/electron
Output:
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/katalin2/node_modules/normalize-url/index.js from /home/katalin2/node_modules/cacheable-request/src/index.js not supported.
Instead change the require of /home/katalin2/node_modules/normalize-url/index.js in /home/katalin2/node_modules/cacheable-request/src/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/katalin2/node_modules/cacheable-request/src/index.js:5:22)
    at Object.<anonymous> (/home/katalin2/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:8:26)
    at Object.<anonymous> (/home/katalin2/node_modules/@electron/get/node_modules/got/source/as-stream.js:4:31)
    at Object.<anonymous> (/home/katalin2/node_modules/@electron/get/node_modules/got/source/create.js:3:18)
    at Object.<anonymous> (/home/katalin2/node_modules/@electron/get/node_modules/got/source/index.js:3:16)
    at Object.<anonymous> (/home/katalin2/node_modules/@electron/get/dist/cjs/GotDownloader.js:15:13)
    at /home/katalin2/node_modules/@electron/get/dist/cjs/downloader-resolver.js:8:66




error Command failed.
Exit code: 1
Command: /root/.nvm/versions/node/v18.2.0/bin/node
Arguments: /root/.nvm/versions/node/v18.2.0/lib/node_modules/yarn/lib/cli.js add sqlite3 --build-from-source --runtime=electron --target=18.2.1 --dist-url=https://electronjs.org/headers
Directory: /home/katalin2/packages/@pb/electron
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
root@shadowvzs-MS-7B86:/home/katalin2# 
```

### Version

i tried the latest but cannot install

### Node.js Version

18.2.0

### How did you install the library?

yarn workspace @pb/electron add sqlite3 --build-from-source --runtime=electron --target=18.2.1 --dist-url=https://electronjs.org/headers

**Comment by daniellockyer** [comment]
This issue looks unrelated to sqlite3 and moreso to do with your use of CJS + ESM 🙂
