### ISSUE TITLE
sqlite3 crash on require with nw.js node.js app

### ISSUE THREAD

**Issue by hayesgr** [TryGhost/node-sqlite3#1753]
### Issue Summary

Appears to be installing wrong module. I am running windows 10. I used npm i sqlite3 -D
the first time. The program crashed application crashed after including the "const sqlite3 = require('sqlite3').verbose();"
It gave no visible error. So I reinstalled sqlite3 without -D. Reran the application and program didn't crash this time but had the error
Uncaught Error: \\?\C:\NodeJS_Projects\App_name\node_modules\sqlite3\build\Release\node_sqlite3.node is not a valid Win32 application.
\\?\C:\NodeJS_Projects\VN_Editor\node_modules\sqlite3\build\Release\node_sqlite3.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1365:18)
    at Module.load (node:internal/modules/cjs/loader:1116:32)
    at Module._load (node:internal/modules/cjs/loader:963:12)
    at Module.require (node:internal/modules/cjs/loader:1140:19)
    at require (node:internal/modules/helpers:128:18)
    at bindings (C:\NodeJS_Projects\VN_Editor\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\NodeJS_Projects\VN_Editor\node_modules\sqlite3\lib\sqlite3-binding.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1258:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1318:10)
    at Module.load (node:internal/modules/cjs/loader:1116:32)

### Steps to Reproduce

Given the error above. I would say to reproduce this just try and install it via npm on a windows system.
The only things I installed was nodejs then nw@sdk and then sqlite3 via npm.

### Version

5.1.7

### Node.js Version

20.11.0

### How did you install the library?

npm i sqlite3

**Comment by woodbri** [comment]
I have the same problem. I have also tried using `import sqlite3 from 'sqlite3';` by adding '"type":"module"` in the package.json file. If I run it with node inspect like:
```
$ node inspect test2
< Debugger listening on ws://127.0.0.1:9229/6ac6169c-e11b-4540-834f-4424cb5ad943
< For help, see: https://nodejs.org/en/docs/inspector
<
connecting to 127.0.0.1:9229 ... ok
Break on start in test2:1
> 1 #!/usr/bin/env node
  2
  3 import sqlite3 from 'sqlite3';
debug> n
debug> There was an internal error in Node.js. Please report this bug.
read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: kill EPERM
    at ChildProcess.kill (node:internal/child_process:512:26)
    at process.handleUnexpectedError (node:internal/debugger/inspect:360:42)
    at process.emit (node:events:531:35)
    at process.emit (node:domain:488:12)
    at process._fatalException (node:internal/process/execution:178:25)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.kill (node:internal/child_process:512:12)
    at process.handleUnexpectedError (node:internal/debugger/inspect:360:42)
    [... lines matching original stack trace ...]
    at process._fatalException (node:internal/process/execution:178:25) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'kill'
}

Node.js v21.7.2
```

```
woodbri@DESKTOP-MD7Q6H6 MINGW64 ~/work/test-sqlite3
$ uname -a
MINGW64_NT-10.0-19045 DESKTOP-MD7Q6H6 3.5.3.x86_64 2024-05-06 06:45 UTC x86_64 Msys

woodbri@DESKTOP-MD7Q6H6 MINGW64 ~/work/test-sqlite3
$ node -v
v21.7.2

woodbri@DESKTOP-MD7Q6H6 MINGW64 ~/work/test-sqlite3
$ npm -v
10.5.0

```

**Comment by woodbri** [comment]
I also tried to load sqlte3@5.1.6 and it also fails with `node -e 'require("sqlite3")` with the following:

```
$ node -e 'require("sqlite3")'
node:internal/modules/cjs/loader:1464
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\msys64\home\woodbri\work\test-sqlite3\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-
x64\node_sqlite3.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1464:18)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\msys64\home\woodbri\work\test-sqlite3\node_modules\sqlite3\lib\sqlite3
-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v21.7.2
```
