### ISSUE TITLE
when i run test my extension get error in init  use sqlite

### ISSUE THREAD

**Issue by makubexxx** [TryGhost/node-sqlite3#1768]
### Issue Summary

my env
    node: v20.11.1
   "sqlite3": "^5.1.7",
  "@types/sqlite3": "^3.1.11",
this is my error info 
2024-03-06 17:41:39.335 [error] Error: Could not locate the bindings file. Tried:
 → D:\work\build\node_sqlite3.node
 → D:\work\build\Debug\node_sqlite3.node
 → D:\work\build\Release\node_sqlite3.node
 → D:\work\out\Debug\node_sqlite3.node
 → D:\work\Debug\node_sqlite3.node
 → D:\work\out\Release\node_sqlite3.node
 → D:\work\Release\node_sqlite3.node
 → D:\work\build\default\node_sqlite3.node
 → D:\work\compiled\18.17.1\win32\x64\node_sqlite3.node
 → D:\work\addon-build\release\install-root\node_sqlite3.node
 → D:\work\addon-build\debug\install-root\node_sqlite3.node
 → D:\work\addon-build\default\install-root\node_sqlite3.node
 → D:\work\lib\binding\node-v118-win32-x64\node_sqlite3.node
	at bindings (d:\code\lowcode-plugin\out\main.js:153:13)
	at node_modules/sqlite3/lib/sqlite3-binding.js (d:\code\lowcode-plugin\out\main.js:213:41)
	at __require (d:\code\lowcode-plugin\out\main.js:12:50)
	at node_modules/sqlite3/lib/sqlite3.js (d:\code\lowcode-plugin\out\main.js:261:20)
	at __require (d:\code\lowcode-plugin\out\main.js:12:50)
	at Object.<anonymous> (d:\code\lowcode-plugin\out\main.js:80583:23)
	at Module._compile (node:internal/modules/cjs/loader:1271:14)
	at Object..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at node:internal/modules/cjs/loader:967:12
	at Function.<anonymous> (node:electron/js2c/node_init:2:13357)
	at h._load (d:\work\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:5634)
	at n._load (d:\work\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:170:29786)
	at t._load (d:\work\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:135:35289)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at require (node:internal/modules/cjs/helpers:121:18)
	at Function.i [as __$__nodeRequire] (d:\work\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at w.vb (d:\work\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:170:30965)
	at async Promise.all (index 0)
should i install c++ tool or python?

### Steps to Reproduce

1. npm install node-sqlite3 its ok
2. but run my extension  get error with Could not locate the bindings file

### Version

5.1.7

### Node.js Version

20.11.1

### How did you install the library?

npm

**Comment by Jim-Elijah** [comment]
solved.  https://github.com/TryGhost/node-sqlite3/issues/1783#issuecomment-2406481228
