### ISSUE TITLE
pnpm i sqlite3  WITH AttributeError: 'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by researchlab** [TryGhost/node-sqlite3#1794]
### Issue Summary

pnpm i sqlite3  WITH AttributeError: 'NoneType' object has no attribute 'groupdict'

### Relevant logs or output

pnpm i sqlite3      
 WARN  10 deprecated subdependencies found: @humanwhocodes/config-array@0.11.14, @humanwhocodes/object-schema@2.0.3, @npmcli/move-file@1.1.2, are-we-there-yet@3.0.1, gauge@4.0.4, glob@7.2.3, inflight@1.0.6, npmlog@6.0.2, rimraf@3.0.2, superagent@8.1.2
Packages: +91 -6
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------
Progress: resolved 769, reused 769, downloaded 0, added 0, done
node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3: Running install script, failed in 6s
.../sqlite3@5.1.7/node_modules/sqlite3 install$ prebuild-install -r napi || node-gyp rebuild
│ prebuild-install warn install Request timed out
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@8.4.1
│ gyp info using node@20.2.0 | darwin | arm64
│ gyp info find Python using Python version 3.11.5 found at "/opt/homebrew/anaconda3/bin/python3"
│ gyp info spawn /opt/homebrew/anaconda3/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/mike/Library/Caches/node-gyp/20.2.0/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/mike/Library/Caches/node-gyp/20.2.0',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/Users/mike/Library/Caches/node-gyp/20.2.0/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
│ No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
│ No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
│ Traceback (most recent call last):
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1502, i…
│     version_list = GetStdoutQuiet(["xcodebuild", "-version"]).splitlines()
│                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1563, i…
│     raise GypError("Error %d running %s" % (job.returncode, cmdlist[0]))
│ gyp.common.GypError: Error 1 running xcodebuild
│ During handling of the above exception, another exception occurred:
│ Traceback (most recent call last):
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
│     sys.exit(gyp.script_main())
│              ^^^^^^^^^^^^^^^^^
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in script…
│     return main(sys.argv[1:])
│            ^^^^^^^^^^^^^^^^^^
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 654, in main
│     return gyp_main(args)
│            ^^^^^^^^^^^^^^
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 639, in gyp_ma…
│     generator.GenerateOutput(flat_list, targets, data, params)
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2455, in…
│     writer.Write(
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 798, in …
│     self.WriteActions(
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 932, in …
│     env = self.GetSortedXcodeEnv()
│           ^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2108, in…
│     return gyp.xcode_emulation.GetSortedXcodeEnv(
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1888, i…
│     env = _GetXcodeEnv(
│           ^^^^^^^^^^^^^
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1743, i…
│     "XCODE_VERSION_ACTUAL": XcodeVersion()[0],
│                             ^^^^^^^^^^^^^^
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1513, i…
│     version = CLTVersion()  # macOS Catalina returns 11.0.0.0.1.1567737322
│               ^^^^^^^^^^^^
│   File "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1551, i…
│     return re.search(regex, output).groupdict()["version"]
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│ AttributeError: 'NoneType' object has no attribute 'groupdict'
│ gyp ERR! configure error 
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/lib/config…
│ gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
│ gyp ERR! System Darwin 23.2.0
│ gyp ERR! command "/usr/local/bin/node" "/Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/bin/node-gyp.js…
│ gyp ERR! cwd /Users/mike/workbench/20240528/water/01-restfulapi/node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3
│ gyp ERR! node -v v20.2.0
│ gyp ERR! node-gyp -v v8.4.1
│ gyp ERR! not ok 

### Version

sqlite3@5.1.7

### Node.js Version

node@20.2.0 

### How did you install the library?

darwin | arm64

**Comment by researchlab** [comment]
it's working after reinstall with the cmd 'pnpm i sqlite3'
