### ISSUE TITLE
Getting a SmartOS prebuilt release

### ISSUE THREAD

**Issue by jacques** [TryGhost/node-sqlite3#290]
```
> sqlite3@2.2.0 install /home/admin/blog/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.2.0-node-v11-sunos-ia32.tar.gz
node-pre-gyp http 404 http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.2.0-node-v11-sunos-ia32.tar.gz
node-pre-gyp ERR! Source compile required: 404 status code downloading tarball 
make: Entering directory `/home/admin/blog/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080200/sqlite3.o
In file included from /usr/include/stdio.h:36:0,
                 from Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:8159:
/opt/local/gcc47/lib/gcc/i386-sun-solaris2.11/4.7.3/include-fixed/sys/feature_tests.h:366:2: error: #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications  require the use of c99"
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c: In function 'porter_stemmer':
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:131970:41: warning: value computed is not used [-Wunused-value]
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:131974:39: warning: value computed is not used [-Wunused-value]
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:131987:35: warning: value computed is not used [-Wunused-value]
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:131992:39: warning: value computed is not used [-Wunused-value]
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:131998:41: warning: value computed is not used [-Wunused-value]
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:132003:39: warning: value computed is not used [-Wunused-value]
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:132012:38: warning: value computed is not used [-Wunused-value]
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:132019:37: warning: value computed is not used [-Wunused-value]
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:132062:39: warning: value computed is not used [-Wunused-value]
Release/obj/gen/sqlite-autoconf-3080200/sqlite3.c:132082:34: warning: value computed is not used [-Wunused-value]
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3080200/sqlite3.o] Error 1
make: Leaving directory `/home/admin/blog/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--fallback-to-build"
gyp ERR! cwd /home/admin/blog/node_modules/sqlite3
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp rebuild --fallback-to-build' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/admin/blog/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:31:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:743:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
node-pre-gyp ERR! System SunOS 5.11
node-pre-gyp ERR! command "node" "/home/admin/blog/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/admin/blog/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.26
node-pre-gyp ERR!  -v v0.2.6
node-pre-gyp ERR! not ok 
npm ERR! sqlite3@2.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@2.2.0 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! System SunOS 5.11
npm ERR! command "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! cwd /home/admin/blog
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/admin/blog/npm-debug.log
npm ERR! not ok code 0
```

**Comment by munir131** [comment]
I am facing same problem with sqlite3@3.1.1 on smartOS
