### ISSUE TITLE
Can't run sqlite3 with Node on Ubuntu 

### ISSUE THREAD

**Issue by emorling** [TryGhost/node-sqlite3#579]
The problem is that in "'/home/relive/relive.photos/node_modules/sqlite3/lib/binding/" i do not have a node-v11-linux-x64, but rather node-v46-linux-x64. 

I am using Nodejs v0.10.25 and Sqlite v3.8.2.

I get the following error.

``` javascript
Error: Cannot find module '/home/relive/relive.photos/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/relive/relive.photos/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Any ideas

**Comment by emorling** [comment]
Is this an error with Ubuntu, NPM, or Sqlite?

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
