### ISSUE TITLE
sqlite3 failing on CentOS-6

### ISSUE THREAD

**Issue by sbbeachvball** [TryGhost/node-sqlite3#588]
I am a relative noob to node.js, but everything is working as expected on my dev machine (Mac OSX 10.10).  The production system is CentOS-6.7, node v4.2.3, sqlite3 v3.1.1 (I tried downgrading to 3.1.0 after finding a thread of a similar issue).  The production machine has a couple other node servers already running on it with no previous issues (but those do not require sqlite3).

I get a stack dump:
Error: Cannot find module '/opt/checkinMaster/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/opt/checkinMaster/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

But the required file seems to exist and is of a reasonable type:
[root@nsleap nodejs]# ll /opt/checkinMaster/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node
-rwxrwxr-x. 1 nsmgmt root 1393304 Sep  9 15:53 /opt/checkinMaster/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node*
[root@nsleap nodejs]# file /opt/checkinMaster/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node
/opt/checkinMaster/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped

sqlite3 is in my package.json and npm install seems to install everything OK.  No issues with any of the requires that happen before the sqlite3 require (express, path, morgan, etc...).

**Comment by sbbeachvball** [comment]
This MAY have been related to the capitialization in my node app name.  I had seen references from "npm init" to that extent, but I used express to generate things and it didn't complain.  I did a couple other operations like completely removing node_modules and forcing "npm install" to recreate entirely from scratch.  Will post back here if I run into this again or definitively narrow this down.  But for now, I think this can be marked as resolved.
