### ISSUE TITLE
Fail on Mac with node v6.0.0

### ISSUE THREAD

**Issue by wgwi** [TryGhost/node-sqlite3#659]
After install with npm install sqlite3 --save, the node told this:Error: Please install sqlite3 package manually
    at new ConnectionManager (/Users/robert/workspace/node/students/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
    at new SqliteDialect (/Users/robert/workspace/node/students/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
    at new Sequelize (/Users/robert/workspace/node/students/node_modules/sequelize/lib/sequelize.js:233:18)
    at Object.<anonymous> (/Users/robert/workspace/node/students/models/index.js:14:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<%

**Comment by DenisCarriere** [comment]
Having the same issue, except I'm trying to use it within an Electron App.

**Comment by daniellockyer** [comment]
Please try with v5.0.3 🙂
