### ISSUE TITLE
"Cannot get property 'sdate' on missing remote object 15" intermittent error in Electron sqlite3 app

### ISSUE THREAD

**Issue by manikantag** [TryGhost/node-sqlite3#742]
Hi,

I m getting below exception in my electron app. I m not sure which is causing this error. This error is not coming all the times, but intermittently.

    angular.js:13594 Error: Cannot get property 'sdate' on missing remote object 15
    Error: Cannot get property 'sdate' on missing remote object 15
        at throwRPCError (d:\electron-app\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:143:17)
        at EventEmitter.<anonymous> (d:\electron-app\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:368:7)
        at emitThree (events.js:116:13)
        at EventEmitter.emit (events.js:194:7)
        at WebContents.<anonymous> (d:\electron-app\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:231:13)
        at emitTwo (events.js:106:13)
        at WebContents.emit (events.js:191:7)
        at metaToValue (d:\electron-app\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:217:13)
        at Object.descriptor.get [as sdate] (d:\electron-app\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:131:16)
        at file:///D:/electron-app/node_modules/lodash/lodash.min.js:8:306
        at e (file:///D:/electron-app/node_modules/lodash/lodash.min.js:5:350)
        at Function.groupBy (file:///D:/electron-app/node_modules/lodash/lodash.min.js:44:488)
        at Function.nest (file:///D:/electron-app/assets/js/mixins.js:307:24)
        at file:///D:/electron-app/node_modules/lodash/lodash.min.js:41:252
        at h (file:///D:/electron-app/node_modules/lodash/lodash.min.js:7:90)
        at Er (file:///D:/electron-app/node_modules/lodash/lodash.min.js:41:220)
        at zn.On.toJSON.On.valueOf.On.value (file:///D:/electron-app/node_modules/lodash/lodash.min.js:136:8)(anonymous function) @ angular.js:13594

Below is the code I've to open, migrate, query records:

    async function initDB() {
        const userDataDir = app.getPath('userData');
        const dbFilePath = path.format({ dir: userDataDir, base: 'sqlite.db' });

        await openDB(
            dbFilePath,
            sqlite3.OPEN_READWRITE | sqlite3.OPEN_CREATE,
            true
        );

        const dbScriptsDir = path.resolve(__dirname + '/../db-scripts');

        await migrateDB(dbScriptsDir);
    }

    async function openDB(dbFilePath, sqliteMode, isSqliteVerbose) {
        console.info(`Initialising sqlite DB, with path:${dbFilePath}, mode:${sqliteMode}, isVerbose:${isSqliteVerbose}`);
        await db.open(dbFilePath, { mode: sqliteMode, verbose: isSqliteVerbose, promise: Promise });
        console.log('Successfully opened sqlite DB', db);
    }

    async function migrateDB(dbScriptsDir) {
        console.info(`Migrating DB (scripts dir: ${dbScriptsDir})...`);
        await db.migrate({ migrationsPath: dbScriptsDir, force__: 'last' });
        console.info('DB migration completed');
    }

    function getData() {
        return db.all('SELECT * FROM userdata');
    }

I m using below stack:

- node-sqlite3 3.1.8, 
- [node-sqlite](https://github.com/kriasoft/node-sqlite) 2.2.3
- Electron 1.4.8 (which has Node: 6.5.0, Chromium: 53.0.2785.143, V8: 5.3.332.47)
- AngularJS 1.5.8
- Lodash 4.17.2
- electron-compile 4.0.2
- bluebird 3.4.6
- [SkelEktron boilerplate](https://github.com/BZCoding/SkelEktron) 0.0.6

Can some please guide me if I m doing something wrong.

**Comment by daniellockyer** [comment]
Please try on the latest version - v5.0.3 - and let us know if there's still an issue 🙂
