### ISSUE TITLE
node_sqlite3 rebuild for electron.js on Windows7 VM

### ISSUE THREAD

**Issue by trimailov** [TryGhost/node-sqlite3#778]
## Goal

Main goal is to build `electron.js` app for Windows, which has `sqlite3` as a dependency. It would be best if I could do this from my main macOS machine.

### Problem

If I do this in straight-forward and naive fashion, i.e. `npm install` and `npm start` (which launches `electron` as in [`electron-quick-start`](https://github.com/electron/electron-quick-start/blob/master/package.json) I receive this error:

![error screenshot](https://cloud.githubusercontent.com/assets/5767952/23093081/1a9708a8-f5e2-11e6-858f-34920631fcd3.PNG)

So far I know that I need to rebuild `node-sqlite3` against `electron` (sorry if I use wrong terminology). Thus I use `electron-rebuild` to rebuild `node-sqlite3`. 

To give more background, I am developing `electron.js` app for personal use, which needs to run on macOS and Windows. My main machine is on macOS. On macOS the `sqlite3` rebuilds for `electron` just fine, though under windows - it does not work. I've tried to build app for windows from macOS, though I get the exact same error as it is shown in the first screenshot (I build executable with `windbuild` script from my `package.json` (link below)).

On Windows 7 Virtual machine I run rebuild with this command (same as on macOS): `electron-rebuild -f -w sqlite3` and I get `gyp ERR! stack Error: read ECONNRESET` error. So this is some kind of a connection problem? In the terminal log I do see this parameter `--host=https://mapbox-node-binary.s3.amazonaws.com` is used - and I cannot access that link through browser. More peculiar thing is that I cannot access that link through my main macOS machine, though rebuild on that machine - works.

#### My package.json

https://gist.github.com/trimailov/3d680b6840a76e0fb83e459fe5c0d3f1

### What I've tried

- Installing python2.7
- Installing MS VS C++ build tools
- Updating powershell from default (AFAIK 2.0) to 4.0
- Setting npm registry to http://registry.npmjs.org (non HTTPS)
- Building `electron.js` app  for windows from macOS as well as on Win7 virtual machine.
- lots of tinkering with node-gyp and some configs, which I've found on the internet and were connected to `ECONNRESET` error, though I am on this for 6hours+ and forgot exactly what commands I've tested.
- Turning off windows firewall completely.
- I do not know what it does exactly, but it may help. I run `node-gyp install` from project's root directory and get this error:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.5.0 | win32 | ia32
gyp http GET https://nodejs.org/download/release/v7.5.0/node-v7.5.0-headers.tar.
gz
gyp http 200 https://nodejs.org/download/release/v7.5.0/node-v7.5.0-headers.tar.
gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1023:11)
gyp ERR! stack     at TLSWrap.onread (net.js:572:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\AppDa
ta\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install"
gyp ERR! cwd C:\Users\IEUser\Documents\GitHub\mano-antradieniai
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

## System setup

Windows 7 32-bit (on VirtualBox, using image for Win7 IE10 from [https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/))
npm 4.2.0
node v7.5.0
python 2.7.13
MS VS C++ build tools 2015

Inside `.npmrc` (set using `npm config set <key> <value>`):
```
python=C:\Python27\python.exe
msvs_version=2015
registry=http://registry.npmjs.org
``` 

### npm cache log file

https://gist.github.com/trimailov/834fff80eb31cfae33dc0ddd1bc85aa5

### Powershell output
```
> antradieniai@0.0.0 rebuild C:\Users\IEUser\Documents\GitHub\mano-antradieniai
> electron-rebuild -f -w sqlite3

x Rebuild Failed
An unhandled error occurred inside electron-rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1023:11)
gyp ERR! stack     at TLSWrap.onread (net.js:572:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\Docum
ents\\GitHub\\mano-antradieniai\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebu
ild" "--target=1.4.15" "--arch=ia32" "--dist-url=https://atom.io/download/electr
on" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\Users\
\IEUser\\Documents\\GitHub\\mano-antradieniai\\node_modules\\sqlite3\\lib\\bindi
ng\\electron-v1.4-win32-ia32" "--host=https://mapbox-node-binary.s3.amazonaws.co
m" "--remote_path=./{name}/v3.1.8/{toolset}/" "--package_name=electron-v1.4-win3
2-ia32.tar.gz"
gyp ERR! cwd C:\Users\IEUser\Documents\GitHub\mano-antradieniai\node_modules\sql
ite3
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1023:11)
gyp ERR! stack     at TLSWrap.onread (net.js:572:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\Docum
ents\\GitHub\\mano-antradieniai\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebu
ild" "--target=1.4.15" "--arch=ia32" "--dist-url=https://atom.io/download/electr
on" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\Users\
\IEUser\\Documents\\GitHub\\mano-antradieniai\\node_modules\\sqlite3\\lib\\bindi
ng\\electron-v1.4-win32-ia32" "--host=https://mapbox-node-binary.s3.amazonaws.co
m" "--remote_path=./{name}/v3.1.8/{toolset}/" "--package_name=electron-v1.4-win3
2-ia32.tar.gz"
gyp ERR! cwd C:\Users\IEUser\Documents\GitHub\mano-antradieniai\node_modules\sqlite3
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber.obs.subscribe.e [as _error] (C:\Users\IEUser\Documents\Git
Hub\mano-antradieniai\node_modules\spawn-rx\lib\index.js:311:43)
    at SafeSubscriber.__tryOrUnsub (C:\Users\IEUser\Documents\GitHub\mano-antrad
ieniai\node_modules\rxjs\Subscriber.js:234:16)
    at SafeSubscriber.error (C:\Users\IEUser\Documents\GitHub\mano-antradieniai\
node_modules\rxjs\Subscriber.js:195:26)
    at Subscriber._error (C:\Users\IEUser\Documents\GitHub\mano-antradieniai\nod
e_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (C:\Users\IEUser\Documents\GitHub\mano-antradieniai\node
_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\Users\IEUser\Documents\GitHub\mano-an
tradieniai\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (C:\Users\IEUser\Documents\GitHub\mano-ant
radieniai\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber.pipesClosed.subscribe [as _next] (C:\Users\IEUser\Document
s\GitHub\mano-antradieniai\node_modules\spawn-rx\lib\index.js:284:42)
    at SafeSubscriber.__tryOrSetError (C:\Users\IEUser\Documents\GitHub\mano-ant
radieniai\node_modules\rxjs\Subscriber.js:243:16)
    at SafeSubscriber.next (C:\Users\IEUser\Documents\GitHub\mano-antradieniai\n
ode_modules\rxjs\Subscriber.js:185:27)
    at Subscriber._next (C:\Users\IEUser\Documents\GitHub\mano-antradieniai\node
_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (C:\Users\IEUser\Documents\GitHub\mano-antradieniai\node_
modules\rxjs\Subscriber.js:89:18)
    at ReduceSubscriber._complete (C:\Users\IEUser\Documents\GitHub\mano-antradi
eniai\node_modules\rxjs\operator\reduce.js:120:30)
    at ReduceSubscriber.Subscriber.complete (C:\Users\IEUser\Documents\GitHub\ma
no-antradieniai\node_modules\rxjs\Subscriber.js:114:18)
    at MergeAllSubscriber._complete (C:\Users\IEUser\Documents\GitHub\mano-antra
dieniai\node_modules\rxjs\operator\mergeAll.js:94:30)
    at MergeAllSubscriber.Subscriber.complete (C:\Users\IEUser\Documents\GitHub\
mano-antradieniai\node_modules\rxjs\Subscriber.js:114:18)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v7.5.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! antradieniai@0.0.0 rebuild: `electron-rebuild -f -w sqlite3`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the antradieniai@0.0.0 rebuild script 'electron-rebuild -f -w
 sqlite3'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antradieniai package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild -f -w sqlite3
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antradieniai
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antradieniai
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IEUser\AppData\Roaming\npm-cache\_logs\2017-02-18T11_44_05
_089Z-debug.log
```

**Comment by jefpmn** [comment]
@trimailov i don't know how to fix your node-gyp problem, but had a same issue with missing `node_sqlite3.node` before. 

my project setup:

```
Ubuntu 16.04
gcc v5.4.0 20160609
npm v4.0.3
node v7.2.1
electron 1.3.1 (electron-packager using version 1.4.2)
electron-vue
```
i fixed the missing `node_sqlite3.node` module by compile it in `ia32` architecture with this command:

```
npm run prepublish && node-gyp configure --module_name=node_sqlite3 --module_path=../lib/binding/electron-v1.4-win32-ia32 && node-gyp rebuild --target=1.4.12 --arch=ia32 --target_platform=win32 --dist-url=https://atom.io/download/atom-shell --module_name=node_sqlite3 --module_path=../lib/binding/electron-v1.4-win32-ia32
```
and it cause warning like this:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.2.1 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ferdinand/Projects/dblskt/app/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ferdinand/.node-gyp/7.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ferdinand/.node-gyp/7.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ferdinand/Projects/dblskt/app/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.2.1 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ferdinand/Projects/dblskt/app/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ferdinand/.node-gyp/iojs-1.4.12/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ferdinand/.node-gyp/iojs-1.4.12',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ferdinand/Projects/dblskt/app/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ferdinand/Projects/dblskt/app/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_sqlite3::Database::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/database.cc:133:96: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
 orceSet(Nan::New("filename").ToLocalChecked(), info[0].As<String>(), ReadOnly);
                                                                              ^
In file included from /home/ferdinand/.node-gyp/iojs-1.4.12/deps/v8/include/v8.h:25:0,
                 from /home/ferdinand/.node-gyp/iojs-1.4.12/src/node.h:42,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
/home/ferdinand/.node-gyp/iojs-1.4.12/deps/v8/include/v8.h:2702:22: note: declared here
                 bool ForceSet(Local<Value> key, Local<Value> value,
                      ^
/home/ferdinand/.node-gyp/iojs-1.4.12/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/database.cc:134:86: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
 .This()->ForceSet(Nan::New("mode").ToLocalChecked(), Nan::New(mode), ReadOnly);
                                                                              ^
In file included from /home/ferdinand/.node-gyp/iojs-1.4.12/deps/v8/include/v8.h:25:0,
                 from /home/ferdinand/.node-gyp/iojs-1.4.12/src/node.h:42,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
/home/ferdinand/.node-gyp/iojs-1.4.12/deps/v8/include/v8.h:2702:22: note: declared here
                 bool ForceSet(Local<Value> key, Local<Value> value,
                      ^
/home/ferdinand/.node-gyp/iojs-1.4.12/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)’:
../src/database.cc:144:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)’:
../src/database.cc:230:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)’:
../src/database.cc:525:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)’:
../src/database.cc:625:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
../src/statement.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_sqlite3::Statement::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/statement.cc:103:74: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
     info.This()->ForceSet(Nan::New("sql").ToLocalChecked(), sql, ReadOnly);
                                                                          ^
In file included from /home/ferdinand/.node-gyp/iojs-1.4.12/deps/v8/include/v8.h:25:0,
                 from /home/ferdinand/.node-gyp/iojs-1.4.12/src/node.h:42,
                 from ../src/statement.cc:2:
/home/ferdinand/.node-gyp/iojs-1.4.12/deps/v8/include/v8.h:2702:22: note: declared here
                 bool ForceSet(Local<Value> key, Local<Value> value,
                      ^
/home/ferdinand/.node-gyp/iojs-1.4.12/deps/v8/include/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginPrepare(node_sqlite3::Database::Baton*)’:
../src/statement.cc:118:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
In file included from ../src/statement.cc:6:0:
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginBind(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:322:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Bind);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginGet(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:370:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Get);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginRun(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:438:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Run);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginAll(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:504:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(All);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginEach(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:601:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Each);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              
         ^
../src/statement.cc:724:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Reset);
     ^
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
  COPY Release/node_sqlite3.node
  COPY ../lib/binding/electron-v1.4-win32-ia32/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/ferdinand/Projects/dblskt/app/node_modules/sqlite3/build'
gyp info ok
```
i suspect that warning was the cause of my app throw an `Error %1 is not valid win32 application` , but i had the `electron-v1.4-win32-ia32` and solve the missing module.

i hope my way to solve the problem giving you a clue why the module is missing.

**Comment by trimailov** [comment]
@jefpmn Thank you for your input, though I have a hunch that it's not the same problem or at least it won't solve mine.

I remember trying to run command like you've recommended (or at least very similar one, with `nan` as dependency), but it does not help. The main thing that I cannot rebuild `node_sqlite3` against `electron` due to:

```
gyp ERR! stack Error: read ECONNRESET
``` 

error. I gett that error with `electron-rebuild` as well as rebuilding by hand with `node-gyp`.

I will try to run you exact recommendation later in the day, though, I will repeat my self, that I cannot rebuild because of `ECONNRESET` error and I do not know exactly why I get it.

**Comment by jefpmn** [comment]
@trimailov already tried [node-pre-gyp](https://github.com/mapbox/node-pre-gyp)?

**Comment by trimailov** [comment]
For both commands 

```
node-gyp configure --module_name=node_sqlite3 --module_path=../lib/binding/electron-v1.4-win32-ia32
```

and

```
node-gyp rebuild --target=1.4.12 --arch=ia32 --target_platform=win32 --dist-url=https://atom.io/download/atom-shell --module_name=node_sqlite3 --module_path=../lib/binding/electron-v1.4-win32-ia32
```

I get this error (which is same or similar `ECONNRESET` error).


```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.5.0 | win32 | ia32
gyp http GET https://nodejs.org/download/release/v7.5.0/node-v7.5.0-headers.tar.
gz
gyp http 200 https://nodejs.org/download/release/v7.5.0/node-v7.5.0-headers.tar.
gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1023:11)
gyp ERR! stack     at TLSWrap.onread (net.js:572:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\AppDa
ta\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--modul
e_name=node_sqlite3" "--module_path=lib\\binding\\electron-v1.4-win32-ia32"
gyp ERR! cwd C:\Users\IEUser\Documents\GitHub\mano-antradieniai\node_modules\sql
ite3
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```


All in all, I do not know why there is problem with this, maybe it's VM? Though the links are opening in browser in VM and host machine just fine, though on rebuild I have connection problems..

Probably I will switch to use another cross-platform GUI stack, even though `electron.js` looks very nice, promising and easy to use.

**Comment by jefpmn** [comment]
@trimailov `node-pre-gyp`, not `node-gyp`

> All in all, I do not know why there is problem with this, maybe it's VM? Though the links are opening in browser in VM and host machine just fine, though on rebuild I have connection problems..

Maybe some configuration error. I see node-gyp when works normal at first time downloading 2 headers, and error that occur on your project environment is only downloading 1 header. Sometimes i didn't trust the Windows's VM environment.

> Probably I will switch to use another cross-platform GUI stack, even though electron.js looks very nice, promising and easy to use.

That was the good solution for this time. My electron project now are ported to Java project.

**Comment by daniellockyer** [comment]
Would you be able to try v5.0.3? 🙂
