### ISSUE TITLE
node-gyp error installing sqlite3

### ISSUE THREAD

**Issue by curiousdevguy** [TryGhost/node-sqlite3#842]
I have been trying to install sqlite3 on my app for the past two days!! no success:
I did: 
`npm install sqlite3 --build-from-source`

**$ node -v
v6.2.0
$ npm -v
3.8.9
$ node-gyp -v
v3.6.2**

```
$ npm install sqlite3 --build-from-source

> sqlite3@3.1.8 install /home/www/project/app/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

(node:9141) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
python: can't open file '/home/www/.node-gyp/6.2.0/tools/gyp/gyp': [Errno 2] No such file or directory
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/nodejs/npm/node_modules/node-gyp/lib/configure.js:350:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.10.23-xxxx-std-ipv6-64
gyp ERR! command "/usr/local/bin/node" "/usr/lib/nodejs/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/www/project/app/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/www/project/app/node_modules/sqlite3/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /home/www/project/app/node_modules/sqlite3
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v0.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/lib/nodejs/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/www/project/app/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/www/project/app/node_modules/sqlite3/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/www/project/app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 3.10.23-xxxx-std-ipv6-64
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/www/project/app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/www/project/app/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/lib/nodejs/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/www/project/app/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/www/project/app/node_modules/sqlite3/lib/binding/node-v48-linux-x64' (1)
npm WARN myApp@1.0.0 No repository field.
npm ERR! Linux 3.10.23-xxxx-std-ipv6-64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3" "--build-from-source"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/www/project/app/npm-debug.log
```

and if I install it normally:

`npm install sqlite3`

and when I run the app, i get the following error:
```
module.js:340
    throw err;
          ^
Error: Cannot find module '/home/www/project/app/node_modules/sqlite3/lib/binding/v8-3.11-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/www/project/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

npm ERR! Linux 3.10.23-xxxx-std-ipv6-64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! myApp@1.0.0 start: `nodejs server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myApp@1.0.0 start script 'nodejs server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the myApp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodejs server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myApp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myApp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/www/project/app/npm-debug.log
```

**Comment by jmikerq** [comment]
same issue with:

node -v: 6.10.3
npm -v: 5.3.0

I have this issue on an ubuntu 14 server, However, I cannot reproduce the issue on my other servers.

**Comment by tuantr10** [comment]
@devnewbieshere @jmikerq have you solved this issue yet? I ran across the same problem:
node v6.11.3
npm v3.10.10
node-gyp v.3.6.2

**Comment by patlachance** [comment]
same issue when trying to install as root in docker container with:
node -v: 9.0.0
npm -v: 5.5.1
docker: 17.10.0-ce

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
