### ISSUE TITLE
can't install node-sqlite3 on window7

### ISSUE THREAD

**Issue by allanruin** [TryGhost/node-sqlite3#843]
I run `npm install sqlite3 --target_arch=ia32` since my nodejs is x86 version `v6.11.0`.I get following terminal output:
```
> sqlite3@3.1.8 install D:\proj\my_app\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  unpack_sqlite_dep
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> D:\proj\my_app\node_modules\sqlite3\build\Release\\sqlite3.lib
  database.cc
  node_sqlite3.cc
  statement.cc
  win_delay_load_hook.cc
..\src\database.cc(133): warning C4996: 'v8::Object::ForceSet': 被声明为已否决 [D:\proj\my_app\node_modules\
sqlite
3\build\node_sqlite3.vcxproj]
  C:\Users\runezhu\.node-gyp\iojs-1.6.11\deps\v8\include\v8.h(2943): note: 参见“v8::Object::ForceSet”的声明
..\src\database.cc(134): warning C4996: 'v8::Object::ForceSet': 被声明为已否决 [D:\proj\my_app\node_modules\
sqlite
3\build\node_sqlite3.vcxproj]
  C:\Users\runezhu\.node-gyp\iojs-1.6.11\deps\v8\include\v8.h(2943): note: 参见“v8::Object::ForceSet”的声明
d:\proj\my_app\node_modules\sqlite3\node_modules\nan\nan_new.h(208): warning C4244: “参数”: 从“sqlite3_int64
”转
换到“double”，可能丢失数据 (编译源文件 ..\src\database.cc) [D:\proj\my_app\node_modules\sqlite3\build\node_s
qlite3.vcxpro
j]
  ..\src\database.cc(502): note: 参见对正在编译的函数 模板 实例化“v8::Local<v8::Number> Nan::New<v8::Number,sqlite3_int6
4>(A0)”的引用
          with
          [
              A0=sqlite3_int64
          ]
..\src\statement.cc(103): warning C4996: 'v8::Object::ForceSet': 被声明为已否决 [D:\proj\my_app\node_modules
\sqlit
e3\build\node_sqlite3.vcxproj]
  C:\Users\runezhu\.node-gyp\iojs-1.6.11\deps\v8\include\v8.h(2943): note: 参见“v8::Object::ForceSet”的声明
..\src\statement.cc(277): warning C4244: “参数”: 从“int64_t”转换到“int”，可能丢失数据 [D:\proj\my_app\node_m
odules\sqlit
e3\build\node_sqlite3.vcxproj]
d:\proj\my_app\node_modules\sqlite3\node_modules\nan\nan_new.h(208): warning C4244: “参数”: 从“sqlite3_int64
”转
换到“double”，可能丢失数据 (编译源文件 ..\src\statement.cc) [D:\proj\my_app\node_modules\sqlite3\build\node_
sqlite3.vcxpr
oj]
  ..\src\statement.cc(479): note: 参见对正在编译的函数 模板 实例化“v8::Local<v8::Number> Nan::New<v8::Number,sqlite3_int
64>(A0)”的引用
          with
          [
              A0=sqlite3_int64
          ]
    正在创建库 D:\proj\my_app\node_modules\sqlite3\build\Release\node_sqlite3.lib 和对象 D:\proj\electron_cl
oud_pay
  \node_modules\sqlite3\build\Release\node_sqlite3.exp
  正在生成代码
  已完成代码的生成
  node_sqlite3.vcxproj -> D:\proj\my_app\node_modules\sqlite3\build\Release\\node_sqlite3.node
  node_sqlite3.vcxproj -> D:\proj\my_app\node_modules\sqlite3\build\Release\node_sqlite3.pdb (Full PDB)
  Copying D:\proj\my_app\node_modules\sqlite3\build\Release\/node_sqlite3.node to D:/proj/electron_cloud_pa
  y/node_modules/sqlite3/lib/binding/electron-v1.6-win32-ia32\node_sqlite3.node
  已复制         1 个文件。
electron-quick-start@1.0.0 D:\proj\my_app
`-- (empty)

npm ERR! code 1

````

I have not seen an error output, except for the last `npm ERR`.

then I run `npm install node-sqlite3`, I get lots of red error, following is just the tail-part of all output.
```
e3\build\node_sqlite3.vcxproj]
  ..\src\nodejs\Statement.cpp(106): note: 类型是“unknown-type”
..\src\nodejs\Statement.cpp(107): error C2248: “v8::HandleScope::HandleScope”: 无法访问 protected 成员(在“v8::HandleScop
e”类中声明
) [D:\proj\my_app\node_modules\node-sqlite3\build\node_sqlite3.vcxproj]
  C:\Users\runezhu\.node-gyp\iojs-1.6.11\deps\v8\include\v8.h(874): note: 参见“v8::HandleScope::HandleScope”的声明
  C:\Users\runezhu\.node-gyp\iojs-1.6.11\deps\v8\include\v8.h(853): note: 参见“v8::HandleScope”的声明
..\src\nodejs\Statement.cpp(107): fatal error C1003: 错误计数超过 100；正在停止编译 [D:\proj\my_app\node_mod
ules\node-sq
lite3\build\node_sqlite3.vcxproj]
d:\proj\my_app\node_modules\node-sqlite3\src\nodejs\NodeFunction.h(13): error C4430: 缺少类型说明符 - 假定为
 int。注意:
C++ 不支持默认 int (编译源文件 ..\src\nodejs\NodeFunction.cpp) [D:\proj\my_app\node_modules\node-sqlite3\bui
ld\node_s
qlite3.vcxproj]
d:\proj\my_app\node_modules\node-sqlite3\src\nodejs\NodeFunction.h(13): error C2143: 语法错误: 缺少“,”(在“&”
的前面) (
编译源文件 ..\src\nodejs\NodeFunction.cpp) [D:\proj\my_app\node_modules\node-sqlite3\build\node_sqlite3.vcxp
roj]
..\src\nodejs\NodeFunction.cpp(35): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [D:\proj\electron
_cloud_pay\node_m
odules\node-sqlite3\build\node_sqlite3.vcxproj]
..\src\nodejs\NodeFunction.cpp(35): error C2143: 语法错误: 缺少“,”(在“&”的前面) [D:\proj\my_app\node_modules
\node-sql
ite3\build\node_sqlite3.vcxproj]
..\src\nodejs\NodeFunction.cpp(37): error C2065: “args”: 未声明的标识符 [D:\proj\my_app\node_modules\node-sq
lite3\
build\node_sqlite3.vcxproj]
..\src\nodejs\NodeFunction.cpp(37): error C2512: “v8::String::Utf8Value::Utf8Value”: 没有合适的默认构造函数可用 [D:\proj
\electron_cl
oud_pay\node_modules\node-sqlite3\build\node_sqlite3.vcxproj]
..\src\nodejs\NodeFunction.cpp(48): error C2065: “args”: 未声明的标识符 [D:\proj\my_app\node_modules\node-sq
lite3\
build\node_sqlite3.vcxproj]
..\src\nodejs\NodeFunction.cpp(48): error C2228: “.Length”的左边必须有类/结构/联合 [D:\proj\my_app\node_modu
les\node-s
qlite3\build\node_sqlite3.vcxproj]
  ..\src\nodejs\NodeFunction.cpp(48): note: 类型是“unknown-type”
..\src\nodejs\NodeFunction.cpp(49): error C2065: “args”: 未声明的标识符 [D:\proj\my_app\node_modules\node-sq
lite3\
build\node_sqlite3.vcxproj]
..\src\nodejs\NodeFunction.cpp(49): error C2227: “->IsFunction”的左边必须指向类/结构/联合/泛型类型 [D:\proj\electron_clo
ud_pay\node_mod
ules\node-sqlite3\build\node_sqlite3.vcxproj]
..\src\nodejs\NodeFunction.cpp(56): error C2065: “args”: 未声明的标识符 [D:\proj\my_app\node_modules\node-sq
lite3\
build\node_sqlite3.vcxproj]
..\src\nodejs\NodeFunction.cpp(56): error C2512: “v8::String::Utf8Value::Utf8Value”: 没有合适的默认构造函数可用 [D:\proj
\electron_cl
oud_pay\node_modules\node-sqlite3\build\node_sqlite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\proj\my_app\node_modules\node-sqlite3
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sqlite3"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sqlite3@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sqlite3@0.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\proj\my_app\npm-debug.log
```

My os is windows7 pro x64(SP1).  Node-sqlite3 does not install the prebuild binary? 

=========update============
I finally install sqlite by using `npm install sqlite --build-from-source=sqlite3`...

**Comment by doamatto** [comment]
If you haven't tried it yet, try installing Windows' build tools via NPM (`npm i -g windows-build-tools`).

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
