### ISSUE TITLE
Nwjs 0.23.7 rebuild problem

### ISSUE THREAD

**Issue by Klemen1337** [TryGhost/node-sqlite3#852]
Hi,
I get an error when trying to rebuild on linux for nwjs 0.23.7 with this command:
```
npm install --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.23.7 --only=prod
```

Does anyone else have the same problem?

Cheers,
K

--------------------
NPM log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/path/.nvm/versions/node/v8.2.1/bin/node',
1 verbose cli   '/path/.nvm/versions/node/v8.2.1/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--build-from-source',
1 verbose cli   '--runtime=node-webkit',
1 verbose cli   '--target_arch=x64',
1 verbose cli   '--target=0.23.7',
1 verbose cli   '--only=prod' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose npm-session 779a0168e288403f
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall sqlite3@3.1.8
7 info lifecycle sqlite3@3.1.8~preinstall: sqlite3@3.1.8
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly currentTree sqlite3@3.1.8
14 silly currentTree ├── abbrev@1.1.0
14 silly currentTree ├─┬ acorn-jsx@3.0.1
14 silly currentTree │ └── acorn@3.3.0
14 silly currentTree ├── acorn@5.0.3
14 silly currentTree ├── ajv-keywords@1.5.1
14 silly currentTree ├── ajv@4.11.8
14 silly currentTree ├── ansi-escapes@1.4.0
14 silly currentTree ├── ansi-regex@2.1.1
14 silly currentTree ├── ansi-styles@2.2.1
14 silly currentTree ├── aproba@1.1.2
14 silly currentTree ├── are-we-there-yet@1.1.4
14 silly currentTree ├── argparse@1.0.9
14 silly currentTree ├── array-union@1.0.2
14 silly currentTree ├── array-uniq@1.0.3
14 silly currentTree ├── arrify@1.0.1
14 silly currentTree ├── asn1@0.2.3
14 silly currentTree ├── assert-plus@0.2.0
14 silly currentTree ├── asynckit@0.4.0
14 silly currentTree ├── aws-sdk@2.65.0
14 silly currentTree ├── aws-sign2@0.6.0
14 silly currentTree ├── aws4@1.6.0
14 silly currentTree ├── balanced-match@0.4.2
14 silly currentTree ├── base64-js@1.2.0
14 silly currentTree ├── bcrypt-pbkdf@1.0.1
14 silly currentTree ├── block-stream@0.0.9
14 silly currentTree ├── boom@2.10.1
14 silly currentTree ├── brace-expansion@1.1.7
14 silly currentTree ├── browser-stdout@1.3.0
14 silly currentTree ├── buffer@5.0.6
14 silly currentTree ├── caller-path@0.1.0
14 silly currentTree ├── callsites@0.2.0
14 silly currentTree ├── caseless@0.12.0
14 silly currentTree ├── chalk@1.1.3
14 silly currentTree ├── circular-json@0.3.1
14 silly currentTree ├── cli-cursor@1.0.2
14 silly currentTree ├── cli-width@2.1.0
14 silly currentTree ├── co@4.6.0
14 silly currentTree ├── code-point-at@1.1.0
14 silly currentTree ├── combined-stream@1.0.5
14 silly currentTree ├── commander@2.9.0
14 silly currentTree ├── concat-map@0.0.1
14 silly currentTree ├── concat-stream@1.6.0
14 silly currentTree ├── console-control-strings@1.1.0
14 silly currentTree ├── core-util-is@1.0.2
14 silly currentTree ├── cryptiles@2.0.5
14 silly currentTree ├── crypto-browserify@1.0.9
14 silly currentTree ├── d@1.0.0
14 silly currentTree ├─┬ dashdash@1.14.1
14 silly currentTree │ └── assert-plus@1.0.0
14 silly currentTree ├── debug@2.6.8
14 silly currentTree ├── deep-extend@0.4.2
14 silly currentTree ├── deep-is@0.1.3
14 silly currentTree ├── del@2.2.2
14 silly currentTree ├── delayed-stream@1.0.0
14 silly currentTree ├── delegates@1.0.0
14 silly currentTree ├── diff@3.2.0
14 silly currentTree ├── doctrine@1.5.0
14 silly currentTree ├── ecc-jsbn@0.1.1
14 silly currentTree ├── es5-ext@0.10.23
14 silly currentTree ├── es6-iterator@2.0.1
14 silly currentTree ├── es6-map@0.1.5
14 silly currentTree ├── es6-set@0.1.5
14 silly currentTree ├── es6-symbol@3.1.1
14 silly currentTree ├── es6-weak-map@2.0.2
14 silly currentTree ├── escape-string-regexp@1.0.5
14 silly currentTree ├── escope@3.6.0
14 silly currentTree ├─┬ eslint@3.5.0
14 silly currentTree │ └── strip-json-comments@1.0.4
14 silly currentTree ├── espree@3.4.3
14 silly currentTree ├── esprima@3.1.3
14 silly currentTree ├─┬ esrecurse@4.1.0
14 silly currentTree │ └── estraverse@4.1.1
14 silly currentTree ├── estraverse@4.2.0
14 silly currentTree ├── esutils@2.0.2
14 silly currentTree ├── event-emitter@0.3.5
14 silly currentTree ├── exit-hook@1.1.1
14 silly currentTree ├── extend@3.0.1
14 silly currentTree ├── extsprintf@1.0.2
14 silly currentTree ├── fast-levenshtein@2.0.6
14 silly currentTree ├── figures@1.7.0
14 silly currentTree ├── file-entry-cache@2.0.0
14 silly currentTree ├── flat-cache@1.2.2
14 silly currentTree ├── forever-agent@0.6.1
14 silly currentTree ├── form-data@2.1.4
14 silly currentTree ├── fs.realpath@1.0.0
14 silly currentTree ├── fstream-ignore@1.0.5
14 silly currentTree ├── fstream@1.0.11
14 silly currentTree ├── gauge@2.7.4
14 silly currentTree ├── generate-function@2.0.0
14 silly currentTree ├── generate-object-property@1.2.0
14 silly currentTree ├─┬ getpass@0.1.7
14 silly currentTree │ └── assert-plus@1.0.0
14 silly currentTree ├── glob@7.1.2
14 silly currentTree ├── globals@9.18.0
14 silly currentTree ├── globby@5.0.0
14 silly currentTree ├── graceful-fs@4.1.11
14 silly currentTree ├── graceful-readlink@1.0.1
14 silly currentTree ├── growl@1.9.2
14 silly currentTree ├── har-schema@1.0.5
14 silly currentTree ├── har-validator@4.2.1
14 silly currentTree ├── has-ansi@2.0.0
14 silly currentTree ├── has-flag@1.0.0
14 silly currentTree ├── has-unicode@2.0.1
14 silly currentTree ├── hawk@3.1.3
14 silly currentTree ├── hoek@2.16.3
14 silly currentTree ├── http-signature@1.1.1
14 silly currentTree ├── ieee754@1.1.8
14 silly currentTree ├── ignore@3.3.3
14 silly currentTree ├── imurmurhash@0.1.4
14 silly currentTree ├── inflight@1.0.6
14 silly currentTree ├── inherits@2.0.3
14 silly currentTree ├── ini@1.3.4
14 silly currentTree ├── inquirer@0.12.0
14 silly currentTree ├── is-fullwidth-code-point@1.0.0
14 silly currentTree ├── is-my-json-valid@2.16.0
14 silly currentTree ├── is-path-cwd@1.0.0
14 silly currentTree ├── is-path-in-cwd@1.0.0
14 silly currentTree ├── is-path-inside@1.0.0
14 silly currentTree ├── is-property@1.0.2
14 silly currentTree ├── is-resolvable@1.0.0
14 silly currentTree ├── is-typedarray@1.0.0
14 silly currentTree ├── isarray@1.0.0
14 silly currentTree ├── isexe@2.0.0
14 silly currentTree ├── isstream@0.1.2
14 silly currentTree ├── jmespath@0.15.0
14 silly currentTree ├── js-yaml@3.8.4
14 silly currentTree ├── jsbn@0.1.1
14 silly currentTree ├── json-schema@0.2.3
14 silly currentTree ├── json-stable-stringify@1.0.1
14 silly currentTree ├── json-stringify-safe@5.0.1
14 silly currentTree ├── json3@3.3.2
14 silly currentTree ├── jsonify@0.0.0
14 silly currentTree ├── jsonpointer@4.0.1
14 silly currentTree ├─┬ jsprim@1.4.0
14 silly currentTree │ └── assert-plus@1.0.0
14 silly currentTree ├── levn@0.3.0
14 silly currentTree ├── lodash._baseassign@3.2.0
14 silly currentTree ├── lodash._basecopy@3.0.1
14 silly currentTree ├── lodash._basecreate@3.0.3
14 silly currentTree ├── lodash._getnative@3.9.1
14 silly currentTree ├── lodash._isiterateecall@3.0.9
14 silly currentTree ├── lodash.create@3.1.1
14 silly currentTree ├── lodash.isarguments@3.1.0
14 silly currentTree ├── lodash.isarray@3.0.4
14 silly currentTree ├── lodash.keys@3.1.2
14 silly currentTree ├── lodash@4.17.4
14 silly currentTree ├── mime-db@1.27.0
14 silly currentTree ├── mime-types@2.1.15
14 silly currentTree ├── minimatch@3.0.4
14 silly currentTree ├── minimist@0.0.8
14 silly currentTree ├── mkdirp@0.5.1
14 silly currentTree ├─┬ mocha@3.4.2
14 silly currentTree │ ├── debug@2.6.0
14 silly currentTree │ ├── glob@7.1.1
14 silly currentTree │ ├── ms@0.7.2
14 silly currentTree │ └── supports-color@3.1.2
14 silly currentTree ├── ms@2.0.0
14 silly currentTree ├── mute-stream@0.0.5
14 silly currentTree ├── nan@2.6.2
14 silly currentTree ├── natural-compare@1.4.0
14 silly currentTree ├─┬ node-gyp@3.6.2
14 silly currentTree │ └── nopt@3.0.6
14 silly currentTree ├── node-pre-gyp@0.6.36
14 silly currentTree ├── nopt@4.0.1
14 silly currentTree ├── npmlog@4.1.0
14 silly currentTree ├── number-is-nan@1.0.1
14 silly currentTree ├── oauth-sign@0.8.2
14 silly currentTree ├── object-assign@4.1.1
14 silly currentTree ├── once@1.4.0
14 silly currentTree ├── onetime@1.1.0
14 silly currentTree ├── optionator@0.8.2
14 silly currentTree ├── os-homedir@1.0.2
14 silly currentTree ├── os-tmpdir@1.0.2
14 silly currentTree ├── osenv@0.1.4
14 silly currentTree ├── path-is-absolute@1.0.1
14 silly currentTree ├── path-is-inside@1.0.2
14 silly currentTree ├── performance-now@0.2.0
14 silly currentTree ├── pify@2.3.0
14 silly currentTree ├── pinkie-promise@2.0.1
14 silly currentTree ├── pinkie@2.0.4
14 silly currentTree ├── pluralize@1.2.1
14 silly currentTree ├── prelude-ls@1.1.2
14 silly currentTree ├── process-nextick-args@1.0.7
14 silly currentTree ├── progress@1.1.8
14 silly currentTree ├── punycode@1.4.1
14 silly currentTree ├── qs@6.4.0
14 silly currentTree ├── querystring@0.2.0
14 silly currentTree ├─┬ rc@1.2.1
14 silly currentTree │ └── minimist@1.2.0
14 silly currentTree ├── readable-stream@2.2.11
14 silly currentTree ├── readline2@1.0.1
14 silly currentTree ├── request@2.81.0
14 silly currentTree ├── require-uncached@1.0.3
14 silly currentTree ├── resolve-from@1.0.1
14 silly currentTree ├── restore-cursor@1.0.1
14 silly currentTree ├── rimraf@2.6.1
14 silly currentTree ├── run-async@0.1.0
14 silly currentTree ├── rx-lite@3.1.2
14 silly currentTree ├── safe-buffer@5.0.1
14 silly currentTree ├── sax@1.2.1
14 silly currentTree ├── semver@5.3.0
14 silly currentTree ├── set-blocking@2.0.0
14 silly currentTree ├── shelljs@0.6.1
14 silly currentTree ├── signal-exit@3.0.2
14 silly currentTree ├── slice-ansi@0.0.4
14 silly currentTree ├── sntp@1.0.9
14 silly currentTree ├── sprintf-js@1.0.3
14 silly currentTree ├─┬ sshpk@1.13.1
14 silly currentTree │ └── assert-plus@1.0.0
14 silly currentTree ├── string_decoder@1.0.2
14 silly currentTree ├── string-width@1.0.2
14 silly currentTree ├── stringstream@0.0.5
14 silly currentTree ├── strip-ansi@3.0.1
14 silly currentTree ├── strip-bom@3.0.0
14 silly currentTree ├── strip-json-comments@2.0.1
14 silly currentTree ├── supports-color@2.0.0
14 silly currentTree ├─┬ table@3.8.3
14 silly currentTree │ ├── is-fullwidth-code-point@2.0.0
14 silly currentTree │ └── string-width@2.0.0
14 silly currentTree ├── tar-pack@3.4.0
14 silly currentTree ├── tar@2.2.1
14 silly currentTree ├── text-table@0.2.0
14 silly currentTree ├── through@2.3.8
14 silly currentTree ├── tough-cookie@2.3.2
14 silly currentTree ├── tryit@1.0.3
14 silly currentTree ├── tunnel-agent@0.6.0
14 silly currentTree ├── tweetnacl@0.14.5
14 silly currentTree ├── type-check@0.3.2
14 silly currentTree ├── typedarray@0.0.6
14 silly currentTree ├── uid-number@0.0.6
14 silly currentTree ├─┬ url@0.10.3
14 silly currentTree │ └── punycode@1.3.2
14 silly currentTree ├── user-home@2.0.0
14 silly currentTree ├── util-deprecate@1.0.2
14 silly currentTree ├── uuid@3.0.1
14 silly currentTree ├── verror@1.3.6
14 silly currentTree ├── which@1.2.14
14 silly currentTree ├── wide-align@1.1.2
14 silly currentTree ├── wordwrap@1.0.0
14 silly currentTree ├── wrappy@1.0.2
14 silly currentTree ├── write@0.2.1
14 silly currentTree ├── xml2js@0.4.17
14 silly currentTree ├── xmlbuilder@4.2.1
14 silly currentTree └── xtend@4.0.1
15 silly idealTree sqlite3@3.1.8
15 silly idealTree ├── abbrev@1.1.0
15 silly idealTree ├─┬ acorn-jsx@3.0.1
15 silly idealTree │ └── acorn@3.3.0
15 silly idealTree ├── acorn@5.0.3
15 silly idealTree ├── ajv-keywords@1.5.1
15 silly idealTree ├── ajv@4.11.8
15 silly idealTree ├── ansi-escapes@1.4.0
15 silly idealTree ├── ansi-regex@2.1.1
15 silly idealTree ├── ansi-styles@2.2.1
15 silly idealTree ├── aproba@1.1.2
15 silly idealTree ├── are-we-there-yet@1.1.4
15 silly idealTree ├── argparse@1.0.9
15 silly idealTree ├── array-union@1.0.2
15 silly idealTree ├── array-uniq@1.0.3
15 silly idealTree ├── arrify@1.0.1
15 silly idealTree ├── asn1@0.2.3
15 silly idealTree ├── assert-plus@0.2.0
15 silly idealTree ├── asynckit@0.4.0
15 silly idealTree ├── aws-sdk@2.65.0
15 silly idealTree ├── aws-sign2@0.6.0
15 silly idealTree ├── aws4@1.6.0
15 silly idealTree ├── balanced-match@0.4.2
15 silly idealTree ├── base64-js@1.2.0
15 silly idealTree ├── bcrypt-pbkdf@1.0.1
15 silly idealTree ├── block-stream@0.0.9
15 silly idealTree ├── boom@2.10.1
15 silly idealTree ├── brace-expansion@1.1.7
15 silly idealTree ├── browser-stdout@1.3.0
15 silly idealTree ├── buffer@5.0.6
15 silly idealTree ├── caller-path@0.1.0
15 silly idealTree ├── callsites@0.2.0
15 silly idealTree ├── caseless@0.12.0
15 silly idealTree ├── chalk@1.1.3
15 silly idealTree ├── circular-json@0.3.1
15 silly idealTree ├── cli-cursor@1.0.2
15 silly idealTree ├── cli-width@2.1.0
15 silly idealTree ├── co@4.6.0
15 silly idealTree ├── code-point-at@1.1.0
15 silly idealTree ├── combined-stream@1.0.5
15 silly idealTree ├── commander@2.9.0
15 silly idealTree ├── concat-map@0.0.1
15 silly idealTree ├── concat-stream@1.6.0
15 silly idealTree ├── console-control-strings@1.1.0
15 silly idealTree ├── core-util-is@1.0.2
15 silly idealTree ├── cryptiles@2.0.5
15 silly idealTree ├── crypto-browserify@1.0.9
15 silly idealTree ├── d@1.0.0
15 silly idealTree ├─┬ dashdash@1.14.1
15 silly idealTree │ └── assert-plus@1.0.0
15 silly idealTree ├── debug@2.6.8
15 silly idealTree ├── deep-extend@0.4.2
15 silly idealTree ├── deep-is@0.1.3
15 silly idealTree ├── del@2.2.2
15 silly idealTree ├── delayed-stream@1.0.0
15 silly idealTree ├── delegates@1.0.0
15 silly idealTree ├── diff@3.2.0
15 silly idealTree ├── doctrine@1.5.0
15 silly idealTree ├── ecc-jsbn@0.1.1
15 silly idealTree ├── es5-ext@0.10.23
15 silly idealTree ├── es6-iterator@2.0.1
15 silly idealTree ├── es6-map@0.1.5
15 silly idealTree ├── es6-set@0.1.5
15 silly idealTree ├── es6-symbol@3.1.1
15 silly idealTree ├── es6-weak-map@2.0.2
15 silly idealTree ├── escape-string-regexp@1.0.5
15 silly idealTree ├── escope@3.6.0
15 silly idealTree ├─┬ eslint@3.5.0
15 silly idealTree │ └── strip-json-comments@1.0.4
15 silly idealTree ├── espree@3.4.3
15 silly idealTree ├── esprima@3.1.3
15 silly idealTree ├─┬ esrecurse@4.1.0
15 silly idealTree │ └── estraverse@4.1.1
15 silly idealTree ├── estraverse@4.2.0
15 silly idealTree ├── esutils@2.0.2
15 silly idealTree ├── event-emitter@0.3.5
15 silly idealTree ├── exit-hook@1.1.1
15 silly idealTree ├── extend@3.0.1
15 silly idealTree ├── extsprintf@1.0.2
15 silly idealTree ├── fast-levenshtein@2.0.6
15 silly idealTree ├── figures@1.7.0
15 silly idealTree ├── file-entry-cache@2.0.0
15 silly idealTree ├── flat-cache@1.2.2
15 silly idealTree ├── forever-agent@0.6.1
15 silly idealTree ├── form-data@2.1.4
15 silly idealTree ├── fs.realpath@1.0.0
15 silly idealTree ├── fstream-ignore@1.0.5
15 silly idealTree ├── fstream@1.0.11
15 silly idealTree ├── gauge@2.7.4
15 silly idealTree ├── generate-function@2.0.0
15 silly idealTree ├── generate-object-property@1.2.0
15 silly idealTree ├─┬ getpass@0.1.7
15 silly idealTree │ └── assert-plus@1.0.0
15 silly idealTree ├── glob@7.1.2
15 silly idealTree ├── globals@9.18.0
15 silly idealTree ├── globby@5.0.0
15 silly idealTree ├── graceful-fs@4.1.11
15 silly idealTree ├── graceful-readlink@1.0.1
15 silly idealTree ├── growl@1.9.2
15 silly idealTree ├── har-schema@1.0.5
15 silly idealTree ├── har-validator@4.2.1
15 silly idealTree ├── has-ansi@2.0.0
15 silly idealTree ├── has-flag@1.0.0
15 silly idealTree ├── has-unicode@2.0.1
15 silly idealTree ├── hawk@3.1.3
15 silly idealTree ├── hoek@2.16.3
15 silly idealTree ├── http-signature@1.1.1
15 silly idealTree ├── ieee754@1.1.8
15 silly idealTree ├── ignore@3.3.3
15 silly idealTree ├── imurmurhash@0.1.4
15 silly idealTree ├── inflight@1.0.6
15 silly idealTree ├── inherits@2.0.3
15 silly idealTree ├── ini@1.3.4
15 silly idealTree ├── inquirer@0.12.0
15 silly idealTree ├── is-fullwidth-code-point@1.0.0
15 silly idealTree ├── is-my-json-valid@2.16.0
15 silly idealTree ├── is-path-cwd@1.0.0
15 silly idealTree ├── is-path-in-cwd@1.0.0
15 silly idealTree ├── is-path-inside@1.0.0
15 silly idealTree ├── is-property@1.0.2
15 silly idealTree ├── is-resolvable@1.0.0
15 silly idealTree ├── is-typedarray@1.0.0
15 silly idealTree ├── isarray@1.0.0
15 silly idealTree ├── isexe@2.0.0
15 silly idealTree ├── isstream@0.1.2
15 silly idealTree ├── jmespath@0.15.0
15 silly idealTree ├── js-yaml@3.8.4
15 silly idealTree ├── jsbn@0.1.1
15 silly idealTree ├── json-schema@0.2.3
15 silly idealTree ├── json-stable-stringify@1.0.1
15 silly idealTree ├── json-stringify-safe@5.0.1
15 silly idealTree ├── json3@3.3.2
15 silly idealTree ├── jsonify@0.0.0
15 silly idealTree ├── jsonpointer@4.0.1
15 silly idealTree ├─┬ jsprim@1.4.0
15 silly idealTree │ └── assert-plus@1.0.0
15 silly idealTree ├── levn@0.3.0
15 silly idealTree ├── lodash._baseassign@3.2.0
15 silly idealTree ├── lodash._basecopy@3.0.1
15 silly idealTree ├── lodash._basecreate@3.0.3
15 silly idealTree ├── lodash._getnative@3.9.1
15 silly idealTree ├── lodash._isiterateecall@3.0.9
15 silly idealTree ├── lodash.create@3.1.1
15 silly idealTree ├── lodash.isarguments@3.1.0
15 silly idealTree ├── lodash.isarray@3.0.4
15 silly idealTree ├── lodash.keys@3.1.2
15 silly idealTree ├── lodash@4.17.4
15 silly idealTree ├── mime-db@1.27.0
15 silly idealTree ├── mime-types@2.1.15
15 silly idealTree ├── minimatch@3.0.4
15 silly idealTree ├── minimist@0.0.8
15 silly idealTree ├── mkdirp@0.5.1
15 silly idealTree ├─┬ mocha@3.4.2
15 silly idealTree │ ├── debug@2.6.0
15 silly idealTree │ ├── glob@7.1.1
15 silly idealTree │ ├── ms@0.7.2
15 silly idealTree │ └── supports-color@3.1.2
15 silly idealTree ├── ms@2.0.0
15 silly idealTree ├── mute-stream@0.0.5
15 silly idealTree ├── nan@2.6.2
15 silly idealTree ├── natural-compare@1.4.0
15 silly idealTree ├─┬ node-gyp@3.6.2
15 silly idealTree │ └── nopt@3.0.6
15 silly idealTree ├── node-pre-gyp@0.6.36
15 silly idealTree ├── nopt@4.0.1
15 silly idealTree ├── npmlog@4.1.0
15 silly idealTree ├── number-is-nan@1.0.1
15 silly idealTree ├── oauth-sign@0.8.2
15 silly idealTree ├── object-assign@4.1.1
15 silly idealTree ├── once@1.4.0
15 silly idealTree ├── onetime@1.1.0
15 silly idealTree ├── optionator@0.8.2
15 silly idealTree ├── os-homedir@1.0.2
15 silly idealTree ├── os-tmpdir@1.0.2
15 silly idealTree ├── osenv@0.1.4
15 silly idealTree ├── path-is-absolute@1.0.1
15 silly idealTree ├── path-is-inside@1.0.2
15 silly idealTree ├── performance-now@0.2.0
15 silly idealTree ├── pify@2.3.0
15 silly idealTree ├── pinkie-promise@2.0.1
15 silly idealTree ├── pinkie@2.0.4
15 silly idealTree ├── pluralize@1.2.1
15 silly idealTree ├── prelude-ls@1.1.2
15 silly idealTree ├── process-nextick-args@1.0.7
15 silly idealTree ├── progress@1.1.8
15 silly idealTree ├── punycode@1.4.1
15 silly idealTree ├── qs@6.4.0
15 silly idealTree ├── querystring@0.2.0
15 silly idealTree ├─┬ rc@1.2.1
15 silly idealTree │ └── minimist@1.2.0
15 silly idealTree ├── readable-stream@2.2.11
15 silly idealTree ├── readline2@1.0.1
15 silly idealTree ├── request@2.81.0
15 silly idealTree ├── require-uncached@1.0.3
15 silly idealTree ├── resolve-from@1.0.1
15 silly idealTree ├── restore-cursor@1.0.1
15 silly idealTree ├── rimraf@2.6.1
15 silly idealTree ├── run-async@0.1.0
15 silly idealTree ├── rx-lite@3.1.2
15 silly idealTree ├── safe-buffer@5.0.1
15 silly idealTree ├── sax@1.2.1
15 silly idealTree ├── semver@5.3.0
15 silly idealTree ├── set-blocking@2.0.0
15 silly idealTree ├── shelljs@0.6.1
15 silly idealTree ├── signal-exit@3.0.2
15 silly idealTree ├── slice-ansi@0.0.4
15 silly idealTree ├── sntp@1.0.9
15 silly idealTree ├── sprintf-js@1.0.3
15 silly idealTree ├─┬ sshpk@1.13.1
15 silly idealTree │ └── assert-plus@1.0.0
15 silly idealTree ├── string_decoder@1.0.2
15 silly idealTree ├── string-width@1.0.2
15 silly idealTree ├── stringstream@0.0.5
15 silly idealTree ├── strip-ansi@3.0.1
15 silly idealTree ├── strip-bom@3.0.0
15 silly idealTree ├── strip-json-comments@2.0.1
15 silly idealTree ├── supports-color@2.0.0
15 silly idealTree ├─┬ table@3.8.3
15 silly idealTree │ ├── is-fullwidth-code-point@2.0.0
15 silly idealTree │ └── string-width@2.0.0
15 silly idealTree ├── tar-pack@3.4.0
15 silly idealTree ├── tar@2.2.1
15 silly idealTree ├── text-table@0.2.0
15 silly idealTree ├── through@2.3.8
15 silly idealTree ├── tough-cookie@2.3.2
15 silly idealTree ├── tryit@1.0.3
15 silly idealTree ├── tunnel-agent@0.6.0
15 silly idealTree ├── tweetnacl@0.14.5
15 silly idealTree ├── type-check@0.3.2
15 silly idealTree ├── typedarray@0.0.6
15 silly idealTree ├── uid-number@0.0.6
15 silly idealTree ├─┬ url@0.10.3
15 silly idealTree │ └── punycode@1.3.2
15 silly idealTree ├── user-home@2.0.0
15 silly idealTree ├── util-deprecate@1.0.2
15 silly idealTree ├── uuid@3.0.1
15 silly idealTree ├── verror@1.3.6
15 silly idealTree ├── which@1.2.14
15 silly idealTree ├── wide-align@1.1.2
15 silly idealTree ├── wordwrap@1.0.0
15 silly idealTree ├── wrappy@1.0.2
15 silly idealTree ├── write@0.2.1
15 silly idealTree ├── xml2js@0.4.17
15 silly idealTree ├── xmlbuilder@4.2.1
15 silly idealTree └── xtend@4.0.1
16 silly install generateActionsToTake
17 silly diff-trees filtering actions: includeDev false includeProd true
18 silly diffTrees action count 0
19 silly decomposeActions action count 0
20 silly install executeActions
21 silly doSerial global-install 0
22 verbose correctMkdir /path/.npm/_locks correctMkdir not in flight; initializing
23 verbose lock using /path/.npm/_locks/staging-bb4c581b77db0741.lock for /path/Projects/Olaii/olaii-nwjs-register/node_modules/sqlite3/node_modules/.staging
24 silly doParallel extract 0
25 silly doReverseSerial unbuild 0
26 silly doSerial remove 0
27 silly doSerial move 0
28 silly doSerial finalize 0
29 silly doParallel refresh-package-json 0
30 silly doParallel preinstall 0
31 silly doSerial build 0
32 silly doSerial global-link 0
33 silly doParallel update-linked 0
34 silly doSerial install 0
35 silly doSerial postinstall 0
36 verbose unlock done using /path/.npm/_locks/staging-bb4c581b77db0741.lock for /path/Projects/Olaii/olaii-nwjs-register/node_modules/sqlite3/node_modules/.staging
37 silly install runPostinstallTopLevelLifecycles
38 silly build sqlite3@3.1.8
39 info linkStuff sqlite3@3.1.8
40 silly linkStuff sqlite3@3.1.8 has /path/Projects/Olaii/olaii-nwjs-register/node_modules as its parent node_modules
41 verbose linkBins sqlite3@3.1.8
42 verbose linkMans sqlite3@3.1.8
43 silly install sqlite3@3.1.8
44 info lifecycle sqlite3@3.1.8~install: sqlite3@3.1.8
45 verbose lifecycle sqlite3@3.1.8~install: unsafe-perm in lifecycle true
46 verbose lifecycle sqlite3@3.1.8~install: PATH: /path/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/node-gyp-bin:/path/Projects/Olaii/olaii-nwjs-register/node_modules/sqlite3/node_modules/.bin:/path/Projects/Olaii/olaii-nwjs-register/node_modules/.bin:/path/.nvm/versions/node/v8.2.1/bin:/path/bin:/path/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
47 verbose lifecycle sqlite3@3.1.8~install: CWD: /path/Projects/Olaii/olaii-nwjs-register/node_modules/sqlite3
48 silly lifecycle sqlite3@3.1.8~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
49 silly lifecycle sqlite3@3.1.8~install: Returned: code: 1  signal: null
50 info lifecycle sqlite3@3.1.8~install: Failed to exec install script
51 verbose stack Error: sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
51 verbose stack Exit status 1
51 verbose stack     at EventEmitter.<anonymous> (/path/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
51 verbose stack     at emitTwo (events.js:125:13)
51 verbose stack     at EventEmitter.emit (events.js:213:7)
51 verbose stack     at ChildProcess.<anonymous> (/path/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
51 verbose stack     at emitTwo (events.js:125:13)
51 verbose stack     at ChildProcess.emit (events.js:213:7)
51 verbose stack     at maybeClose (internal/child_process.js:921:16)
51 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
52 verbose pkgid sqlite3@3.1.8
53 verbose cwd /path/Projects/Olaii/olaii-nwjs-register/node_modules/sqlite3
54 verbose Linux 4.4.0-83-generic
55 verbose argv "/path/.nvm/versions/node/v8.2.1/bin/node" "/path/.nvm/versions/node/v8.2.1/bin/npm" "install" "--build-from-source" "--runtime=node-webkit" "--target_arch=x64" "--target=0.23.7" "--only=prod"
56 verbose node v8.2.1
57 verbose npm  v5.3.0
58 error code ELIFECYCLE
59 error errno 1
60 error sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
60 error Exit status 1
61 error Failed at the sqlite3@3.1.8 install script.
61 error This is probably not a problem with npm. There is likely additional logging output above.
62 verbose exit [ 1, true ]
```

**Comment by Klemen1337** [comment]
Fixed with this https://github.com/nwjs/nw.js/issues/5960

**Comment by daniellockyer** [comment]
Would you be able to try with the latest version - v5.0.3? 🙂
